modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
This PR is an updated version of this one https://github.com/neo4j/docs-operations/pull/608 after the detachment of forks.
=> Adding more context to the `sub` information on the SSO tutorial

modules/ROOT/pages/monitoring/metrics/reference.adoc
We have recently introduced metrics that track the states databases are in on a server. This PR updates the docs to reflect this.
=> Add database state metrics

modules/ROOT/pages/authentication-authorization/access-control.adoc, modules/ROOT/pages/authentication-authorization/built-in-roles.adoc, modules/ROOT/pages/authentication-authorization/introduction.adoc, modules/ROOT/pages/authentication-authorization/ldap-integration.adoc, modules/ROOT/pages/authentication-authorization/manage-execute-permissions.adoc, modules/ROOT/pages/authentication-authorization/sso-integration.adoc, modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/clustering/servers.adoc, modules/ROOT/pages/composite-databases/introduction.adoc, modules/ROOT/pages/manage-databases/configuration.adoc, modules/ROOT/pages/manage-databases/errors.adoc, modules/ROOT/pages/manage-databases/introduction.adoc, modules/ROOT/pages/manage-databases/queries.adoc, modules/ROOT/pages/manage-databases/remote-alias.adoc, modules/ROOT/pages/monitoring/query-management.adoc, modules/ROOT/pages/monitoring/transaction-management.adoc, modules/ROOT/pages/reference/procedures.adoc, modules/ROOT/pages/routing-decisions.adoc, modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
Corresponding PR (with more information) in Cypher Manual:
https://github.com/neo4j/docs-cypher/pull/494
=> Update links to new Cypher Manual Administration chapter 

modules/ROOT/pages/docker/introduction.adoc
The environment variable `NEO4J_AUTH` was spelled as `NEO4J_ATUH`
=> Fix typo in docker introduction

modules/ROOT/pages/authentication-authorization/sso-integration.adoc
The groups config item gained support for a single string in 5.4.0 so we should reflect that. Also explain in more detail what is supported.
=> Better document the username and groups config items

modules/ROOT/pages/authentication-authorization/sso-integration.adoc
The groups config item gained support for a single string in 5.4.0 so we should reflect that. Also explain in more detail what is supported.
Cherry-picked from #674
=> Better document the username and groups config items (#674)

modules/ROOT/pages/clustering/index.adoc
It wasn't listed in the table of contents there though the page is in the left-side menu
=> Add page monitoring cluster endpoints to the index

modules/ROOT/pages/clustering/disaster-recovery.adoc
Recently in 5.7 we updated the error message when attempting to deallocate a server hosting a database with only 1 primary. This PR updates the disaster recovery guide to reflect this.
=> Update disaster recovery guide to reflect error message change

modules/ROOT/pages/clustering/disaster-recovery.adoc
Recently in 5.7 we updated the error message when attempting to deallocate a server hosting a database with only 1 primary. This PR updates the disaster recovery guide to reflect this.
---------
=> Update disaster recovery guide to reflect error message change (#709)

modules/ROOT/pages/reference/configuration-settings.adoc
The off-heap memory block contains a lot more than transaction state (netty, lucene etc.) so the config setting 'server.memory.off_heap.max_size' has been renamed to 'server.memory.off_heap.transaction_max_size' to make it clearer that it only applies to transaction state.
=> Rename server.memory.off_heap.max_size to server.memory.off_heap.transaction_max_size

modules/ROOT/pages/installation/linux/debian.adoc
I moved the section to AFTER installation instead of the java pre-requisites because it's something that will only happen *after* neo4j is installed.
=> updated section about if java 19 is accidentally installed

modules/ROOT/pages/reference/configuration-settings.adoc
=> server.db.query_cache_size has been deprecated in 5.7 (#726)

modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Cypher Manual PR: https://github.com/neo4j/docs-cypher/pull/516
=> Update links to new Values and Types chapter in Cypher Manual

modules/ROOT/pages/installation/linux/debian.adoc, modules/ROOT/pages/installation/requirements.adoc
In 5.x, the link is not included anymore, thus the decision to remove it here.
=> Removing link to backports as it is broken

modules/ROOT/pages/clustering/internals.adoc
It alone does not communicate much meaning, so removing this for now as more context is provided.
=> Removing sentence as requested

modules/ROOT/pages/installation/linux/debian.adoc, modules/ROOT/pages/installation/requirements.adoc
In 5.x, the link is not included anymore, thus the decision to remove it here.
Cherry-picked from https://github.com/neo4j/docs-operations/pull/762
=> Removing link to backports as it is broken (#762)

modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc, modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc, modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc, modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-memrec.adoc, modules/ROOT/pages/tools/neo4j-admin/unbind.adoc, modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Small changes to match the help pages of the commands.
Info on testing: https://github.com/neo4j/docs-testing/blob/operations/operations/README.md
Sister PR for help pages: https://github.com/neo-technology/neo4j/pull/20600
=> Sync `neo4j-admin` commands (Tools section) with help pages

modules/ROOT/pages/security/ssl-framework.adoc
I think we should mention to include the certificate chain in the `public.crt` file for clients to be able to verify them properly.
---------
Cherry-picked from #778
=> Update ssl-framework.adoc (#778)

modules/ROOT/pages/clustering/internals.adoc, modules/ROOT/partials/neo4j-config/all-settings.adoc
From Petr,
> The fact that server-side-routing uses Java driver is an internal detail. One cluster member forwards the query to another cluster member. The fact that it uses Java driver to do that is an implementation detail.
that's the reason for the change in the first sentence.
Sister PR: https://github.com/neo4j/docs-operations/pull/779
=> Polish server side routing information and settings.

modules/ROOT/pages/clustering/setup/routing.adoc
From Petr,
> The fact that server-side-routing uses Java driver is an internal detail. One cluster member forwards the query to another cluster member. The fact that it uses Java driver to do that is an implementation detail.
that's the reason for the change in the first sentence.
Sister PR: https://github.com/neo4j/docs-operations/pull/780
=> Polish server side routing information.

modules/ROOT/pages/clustering/databases.adoc
Adds a note on what allocation numbers are used if `TOPOLOGY` is not set.
---------
Cherry-picked from #797
=> Creating a database without specifying topology (#797)

modules/ROOT/pages/configuration/configuration-settings.adoc
Setting this to 1 didn't work, so the constraint has been changed in https://github.com/neo-technology/neo4j/pull/20735.
=> Update minimum value for minimum system primaries

modules/ROOT/pages/configuration/configuration-settings.adoc
Setting this to 1 didn't work, so the constraint has been changed in https://github.com/neo-technology/neo4j/pull/20735.
=> Update minimum value for minimum system primaries (#809)

modules/ROOT/pages/reference/procedures.adoc
This PR deprecates the following procedures:
- `dbms.upgrade`
- `dbms.upgradeStatus`
=> Deprecate upgrade procedures

modules/ROOT/pages/performance/memory-configuration.adoc
Fixing small typo spotted while reading that page.
=> fixed neoj4 <> neo4j typo in memory config docs

modules/ROOT/pages/performance/memory-configuration.adoc
Fixing small typo spotted while reading that page.
Cherry-picked from #815
=> fixed neoj4 <> neo4j typo in memory config docs (#815)

modules/ROOT/pages/composite-databases/index.adoc
We are expected to support compatibility with minor versions only, but will not actively prevent major version combinations.
This applies to all 5.x and later series.
=> Add compatibility guarantee for composite databases

modules/ROOT/pages/composite-databases/index.adoc
We are expected to support compatibility with minor versions only, but will not actively prevent major version combinations.
This applies to all 5.x and later series.
---------
Cherry-picked from #805
=> Add compatibility guarantee for composite databases (#805)

modules/ROOT/pages/configuration/configuration-settings.adoc
=> Add collapse nested JSON objects in the query logger when db.logs.query.annotation_data_as_json_enabled setting is true

modules/ROOT/pages/configuration/configuration-settings.adoc
=> Update db.tx_log.rotation.retention_policy to include period-based transaction log pruning strategy with max size restriction

modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Has always been enterprise only, but it is not obvious from just looking at the command docs.
=> Mark incremental import as enterprise only

modules/ROOT/content-nav.adoc, modules/ROOT/pages/clustering/clustering-advanced/default-database.adoc, modules/ROOT/pages/clustering/clustering-advanced/index.adoc, modules/ROOT/pages/clustering/clustering-advanced/reconciler.adoc
This was in the 'Clustering internals' page in 4.4, but needed updating for 5.x, and making more useful.
=> Add a page about the reconciler pattern in a clustered DBMS

modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/reference/procedures.adoc
The ability to automatically enable free servers results in the following docs change: 
1. Addition of a config setting `initial.dbms.automatically_enable_free_servers`
2. Adjustment of `dbms.showTopologyGraphConfig()` procedure's output
3. Introduction of `dbms.cluster.setAutomaticallyEnableFreeServers()` procedure
=> Automatically enable free servers

modules/ROOT/pages/installation/requirements.adoc
Debian 12 was released recently, and so we should support it.
=> added debian 12 to the list of supported operating systems

modules/ROOT/pages/installation/requirements.adoc
Debian 12 was released recently, and so we should support it.
Cherry-picked from #896
=> added debian 12 to the list of supported operating systems (#896)

modules/ROOT/content-nav.adoc, modules/ROOT/pages/clustering/index.adoc, modules/ROOT/pages/clustering/setup/single-to-cluster.adoc
This PR adds documentation on how a user can move from a deployment with a single system primary server to a cluster deployment.
=> Document how to move from single to cluster

modules/ROOT/pages/backup-restore/online-backup.adoc
The table headers in the online backup docs have the wrong order for `Description` and `Default`, this PR fixes it.
=> [online backup] database parameter table headers fix

modules/ROOT/pages/clustering/databases.adoc
The section for retrieving the serverId here https://neo4j.com/docs/operations-manual/current/clustering/databases/#cluster-designated-seeder is not correct.
The docs use `SHOW SERVERS` which will return the name of the server, by default it has the same name as the serverId, but in case servers were renamed, using 
```
RENAME SERVER `25a7efc7-d063-44b8-bdee-f23357f89f01` TO `primary1` 
```
then it will not match anymore and trying to use `primary1` as serverId while following the documentation will lead to the following exception when seeding a cluster :
```
Could not create database with specified existingDataSeedInstance 'optimus-001'. Expected server uuid string.
```
This PR ensures that the correct serverId is returned when following the documentation.
=> fix retrieving serverId command for seed cluster section

modules/ROOT/pages/clustering/databases.adoc
The section for retrieving the serverId here
https://neo4j.com/docs/operations-manual/current/clustering/databases/#cluster-designated-seeder is not correct.
The docs use `SHOW SERVERS` which will return the name of the server, by default it has the same name as the serverId, but in case servers were renamed, using
```
RENAME SERVER `25a7efc7-d063-44b8-bdee-f23357f89f01` TO `primary1` 
```
then it will not match anymore and trying to use `primary1` as serverId while following the documentation will lead to the following exception when seeding a cluster :
```
Could not create database with specified existingDataSeedInstance 'optimus-001'. Expected server uuid string.
```
This PR ensures that the correct serverId is returned when following the documentation.
=> fix retrieving serverId command for seed cluster section (#904)

modules/ROOT/pages/security/ssl-framework.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/907
=> Removing obsolete encryption arguments (#907)

modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/reference/procedures.adoc
The ability to automatically enable free servers results in the following docs change:
1. Addition of a config setting `initial.dbms.automatically_enable_free_servers`
2. Adjustment of `dbms.showTopologyGraphConfig()` procedure's output
3. Introduction of `dbms.cluster.setAutomaticallyEnableFreeServers()` procedure
Cherry-picked from #837
=> Automatically enable free servers #837

modules/ROOT/pages/composite-databases/administration.adoc, modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Companion PR to https://github.com/neo4j/docs-cypher/pull/649.
Column added in 5.11 and I assume docs is currently pointing to 5.10 so I'll leave this as a draft PR until 5.10 is released and docs branch switched.
=> Add new column `composite` to `SHOW ALIASES`

modules/ROOT/pages/installation/linux/tarball.adoc
The documentation for neo4j.service systemctl was invalid. 
The command "systemctl daemon-reload" must not be part of the neo4j.service definition.
=> Fix systemctl enable neo4j.service documentation

modules/ROOT/pages/installation/linux/tarball.adoc
The documentation for neo4j.service systemctl was invalid.  The command "systemctl daemon-reload" must not be part of the neo4j.service definition.
Cherry-picked from #903
=> Fix systemctl enable neo4j.service documentation (#903)

modules/ROOT/pages/security/ssl-framework.adoc
The SSL Framework page (https://neo4j.com/docs/operations-manual/5/security/ssl-framework/ ) does not mention port 7688 (Server Side Routing).
This port would be encrypted if you use the cluster policy (or Bolt).
We should add that to the documentation to eliminate any possible confusion.
=> Adding information about port 7688

modules/ROOT/pages/monitoring/metrics/reference.adoc
=> Improve the description of the metric cluster.raft.message_processing_delay

modules/ROOT/pages/configuration/configuration-settings.adoc
Add space after `2` before `days`
=> Fix an error in example for `db.tx_log.rotation.retention_policy`

modules/ROOT/pages/configuration/configuration-settings.adoc
Add space after `2` before `days`
=> Fix an error in example for `db.tx_log.rotation.retention_policy` (#988)

modules/ROOT/pages/clustering/databases.adoc
Be explicit around `CREATE/ALTER DATABASE` that one does not need to call `REALLOCATE` after every allocation operation. 
For `ALTER SERVER` and `DEALLOCATE DATABASES` this already seems clear.
=> Be explicit that reallocate is optional

modules/ROOT/content-nav.adoc, modules/ROOT/pages/configuration/file-locations.adoc, modules/ROOT/pages/configuration/plugins.adoc, modules/ROOT/pages/docker/backup-restore.adoc, modules/ROOT/pages/docker/configuration.adoc, modules/ROOT/pages/docker/dump-load.adoc, modules/ROOT/pages/docker/index.adoc, modules/ROOT/pages/docker/introduction.adoc, modules/ROOT/pages/docker/mounting-volumes.adoc, modules/ROOT/pages/docker/operations.adoc, modules/ROOT/pages/docker/plugins.adoc, modules/ROOT/pages/docker/security.adoc
changes include:
* separated maintenance.adoc into 2 separate pages, for backup/restore and dump/load.
* new information about tagging, now that we have both debian and redhat images
* documentation for mount points and what they do, including cross references to other parts of the docker doc.
* Neo4j admin report usage
* a dedicated page about plugins. Most of this is taken from operations.adoc about user defined procedures.
I still need to add documentation for the `EXTENDED_CONF` feature which lets you do `--expand-commands`. But while I was writing the doc I realised the feature is terrible and needs renaming and fixing, so that change is still to come.
=> Restructured Docker section and added documentation about mount points and plugins

modules/ROOT/content-nav.adoc, modules/ROOT/pages/configuration/file-locations.adoc, modules/ROOT/pages/configuration/plugins.adoc, modules/ROOT/pages/docker/backup-restore.adoc, modules/ROOT/pages/docker/configuration.adoc, modules/ROOT/pages/docker/dump-load.adoc, modules/ROOT/pages/docker/index.adoc, modules/ROOT/pages/docker/introduction.adoc, modules/ROOT/pages/docker/mounting-volumes.adoc, modules/ROOT/pages/docker/operations.adoc, modules/ROOT/pages/docker/plugins.adoc, modules/ROOT/pages/docker/security.adoc
Cherry-picked from #973 
changes include:
* separated maintenance.adoc into 2 separate pages, for backup/restore and dump/load.
* new information about tagging, now that we have both debian and redhat images
* documentation for mount points and what they do, including cross references to other parts of the docker doc.
* Neo4j admin report usage
* a dedicated page about plugins. Most of this is taken from operations.adoc about user defined procedures.
I still need to add documentation for the `EXTENDED_CONF` feature which lets you do `--expand-commands`. But while I was writing the doc I realised the feature is terrible and needs renaming and fixing, so that change is still to come.
---------
=> Restructured Docker section and added documentation about mount points and plugins (#973)

modules/ROOT/pages/reference/procedures.adoc
We are updating the signatures of procedures to match the defaults of the new Cypher Types
Continuation of: https://github.com/neo4j/docs-cypher/pull/676
=> Update procedures and functions signatures

modules/ROOT/pages/configuration/configuration-settings.adoc
Default binding timeout is 24h not 10m.
=> Align default binding timeout

modules/ROOT/pages/configuration/configuration-settings.adoc
Default binding timeout is 24h not 10m.
Cherry-picked from #1050
=> Align default binding timeout (#1050)

modules/ROOT/pages/authentication-authorization/dbms-administration.adoc, modules/ROOT/pages/authentication-authorization/manage-execute-permissions.adoc
[Re-document the split of EXECUTE and EXECUTE BOOSTED privileges](https://github.com/neo4j/docs-cypher/pull/733/files#top)
=> Port content from the cypher manual #733

modules/ROOT/pages/reference/procedures.adoc
in an attempt to clarify better what is needed and updating the link to point to the `EXECUTE` privileges instead of just general privilege handling.
Also included some other procedure related things I noticed:
* Add `Admin only` label to the @admin cdc procedure
* Added `introduced in` and `beta` labels to the procedure description section for cdc procedures (like how it was done for vector index procedures)
* Remove removed procedure from procedure description (only one of the removed procedures still had description table)
=> Update note about needed privileges for @admin procedures on the procedures page

modules/ROOT/pages/kubernetes/plugins.adoc
Hello,
Looks like in order to have the apoc plugin installed, the NEO4J_PLUGINS env must be set and this was not apparent from the documentation.
=> added additional step to set NEO4J_PLUGINS env

modules/ROOT/pages/database-internals/transaction-logs.adoc
Add more details on how to combine both temporal and size parameters for the Tx log retention.
=> Add temporal and size parameters for `db.tx_log.rotation.retention_policy`

modules/ROOT/pages/database-internals/transaction-logs.adoc
Add more details on how to combine both temporal and size parameters for the Tx log retention.
=> Add temporal and size parameters for `db.tx_log.rotation.retention_policy` (#1077)

modules/ROOT/pages/installation/linux/rpm.adoc, modules/ROOT/pages/installation/requirements.adoc
Cherry-picked from #1074 and updated.
=> added rhel 9.2 support to list and improved instructions around non-interactive rpm installation 

modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/reference/procedures.adoc
The parallel runtime introduced a new config setting. For testing purposes, I have taken the description from the mono repo verbatim (https://github.com/neo-technology/neo4j/pull/22275/files#diff-22e5a6968aee5ed485e16da8650e784a16dbd787005216bb719d3dc44aa2b43a)
There are also a number of procedures that are not considered thread-safe to run on the parallel runtime. This PR adds a note for the relevant procedures. Note that the link to the Cypher Manual will not work yet as the we have yet to merge the parallel runtime PR in that repo.
=> Add parallel runtime information

modules/ROOT/pages/database-internals/transaction-management.adoc
Following the slack discussions and findings, I suggest the following amendments.
Do we have then to cherry-pick this PR to the branch 5.x to make it visible now?
=> Update information on `db.transaction.timeout`

modules/ROOT/pages/database-internals/transaction-management.adoc
Following the slack discussions and findings, I suggest the following amendments.
Do we have then to cherry-pick this PR to the branch 5.x to make it visible now?
---------
=> Update information on `db.transaction.timeout` (#1085)

modules/ROOT/pages/installation/requirements.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1088
=> Adding information about JRE (#1088)

modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
2^32 labels has never actually been supported,
anything over 2^31 would fail with an integer overflow.
=> Correct max label id

modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
2^32 labels has never actually been supported,
anything over 2^31 would fail with an integer overflow.
Cherry-picked from #1176
=> Correct max label id (#1176)

modules/ROOT/pages/security/ssl-framework.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1177
=> Improvement of instructions for SSL configuration (#1177)

modules/ROOT/pages/docker/ref-settings.adoc
I was getting an error when using the original variable name, but removing one `_` from each side of `ldap` seems to have fixed it. Can anyone else also confirm that?
=> Docker - ref-settings.adoc: NEO4J_dbms_security_ldap_host typo error

modules/ROOT/pages/docker/ref-settings.adoc
=> Docker - ref-settings.adoc: NEO4J_dbms_security_ldap_host typo error 

antora.yml, modules/ROOT/pages/installation/requirements.adoc
Cherry-picked from  #1192 and #1150
=> Cherry-picks all 5.14 features from dev

modules/ROOT/pages/monitoring/metrics/reference.adoc
In terms of our testing project, update the metrics, their classes and descriptions. All changes are made according to the file _metrics_without_descriptions.txt_
=> Udate metrics according to the test results (#1195)

modules/ROOT/pages/monitoring/metrics/reference.adoc
Update the metric's description according to the codebase
=> Update the description of `<prefix>.cluster.raft.message_processing_timer`

modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
added with `LOAD ON ALL DATA` but was missed when it was documented
Cherry-picked from #1215
=> Add new target for `SHOW SUPPORTED PRIVILEGES` (#1215)

modules/ROOT/pages/kubernetes/plugins.adoc
Removed the section where we installed apoc with the env ["apoc"].  This is not needed if we are just pointing to the file in labs.
=> Update plugins.adoc in Kubernetes

modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/database-internals/transaction-logs.adoc
In Neo4j 5.13, the def.value of the config `db.tx_log.rotation.retention_policy` was changed from `2 days` to `2 days 2G`. To reflect those changes, we have to update two pages in the Operations manual.
=> Update the default value of `db.tx_log.rotation.retention_policy`

modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/database-internals/transaction-logs.adoc
In Neo4j 5.13, the def.value of the config
`db.tx_log.rotation.retention_policy` was changed from `2 days` to `2 days 2G`. To reflect those changes, we have to update two pages in the Operations manual.
---------
=> Update the default value of `db.tx_log.rotation.retention_policy` (#1239)

modules/ROOT/pages/tools/neo4j-admin/validate-config.adoc
As written the example throws the following error with 5.14 @ [Validate Config](https://neo4j.com/docs/operations-manual/5/tools/neo4j-admin/validate-config/):
```
./bin/neo4j-admin validate-config
Unmatched argument at index 0: 'validate-config'
Did you mean: neo4j-admin server validate-config or neo4j-admin server migrate-configuration or neo4j-admin database migrate?
```
=> Fix neo4j-admin server validate-config example

modules/ROOT/pages/introduction.adoc
Cherry-picked and adapted from https://github.com/neo4j/docs-operations/pull/1258
=> Restructure of the introduction page (#1258)

modules/ROOT/content-nav.adoc, modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc, modules/ROOT/pages/configuration/index.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1260
=> Moving the password page to auth (#1260)

modules/ROOT/pages/database-internals/locks-deadlocks.adoc
The reason I moved the Note, was because it wasn't clear which section the Note refers to.
=> Clarify lock note again

modules/ROOT/pages/configuration/connectors.adoc
=> Rename Neo4j connectors to network connectors to differentiate them from Kafka, Spark, etc. (#1301)

modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Add a note to ensure the Neo4j server is able to connect to the identity provider, as this is required for operation.
=> Add a note about Idp connectivity

modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Add a note to ensure the Neo4j server is able to connect to the identity provider, as this is required for operation.
---------
=> Add a note about Idp connectivity (#1329)

modules/ROOT/pages/clustering/servers.adoc
The operations manual refers to the `Deallocated` state as it was always available. Actually it is a rather new invention, so it is worth pointing out that to the reader.
=> Tag deallocated state with version

modules/ROOT/pages/monitoring/metrics/reference.adoc
According to the [PR#22820](https://github.com/neo-technology/neo4j/pull/22820), we have to update information about metrics: add a new one and label deprecated metrics.
A new metric is `<prefix>.neo4j.count.relationship_types`.
=> Add a metric for block format

modules/ROOT/pages/monitoring/metrics/reference.adoc
According to the
[PR#22820](https://github.com/neo-technology/neo4j/pull/22820), we have to update information about metrics: add a new one and label deprecated metrics.
A new metric is `<prefix>.neo4j.count.relationship_types`.
=> Add a metric for block format (#1358)

modules/ROOT/pages/monitoring/metrics/reference.adoc
Add two new metrics according to the https://github.com/neo-technology/neo4j/pull/23748
=> Add new metrics to count page flushed by background evictor

modules/ROOT/pages/database-administration/index.adoc
Apparently the lack of extension didn't allow the redirect to catch up. It could be that or the addition of a `/` in the end...
=> Fixing persisting 404 error

modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
I was reading the immutable privileges tutorial at https://neo4j.com/docs/operations-manual/current/tutorial/tutorial-immutable-privileges/ and noticed two typos, `lxref` instead of `xref`, this PR fixes it.
=> fix lxref instead of xref in immutable privileges tutorial

modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
I was reading the immutable privileges tutorial at https://neo4j.com/docs/operations-manual/current/tutorial/tutorial-immutable-privileges/ and noticed two typos, `lxref` instead of `xref`, this PR fixes it.
=> fix lxref instead of xref in immutable privileges tutorial (#1347)

modules/ROOT/pages/authentication-authorization/built-in-roles.adoc, modules/ROOT/pages/authentication-authorization/index.adoc, modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc, modules/ROOT/pages/configuration/command-expansion.adoc, modules/ROOT/pages/database-administration/aliases/remote-database-alias-configuration.adoc, modules/ROOT/pages/database-administration/composite-databases/concepts.adoc, modules/ROOT/pages/database-administration/composite-databases/manage-composite-databases.adoc, modules/ROOT/pages/database-administration/composite-databases/querying-composite-databases.adoc, modules/ROOT/pages/database-administration/composite-databases/sharding-with-copy.adoc, modules/ROOT/pages/database-administration/index.adoc, modules/ROOT/pages/database-administration/standard-databases/configuration-parameters.adoc, modules/ROOT/pages/database-administration/standard-databases/errors.adoc, modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc, modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc, modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
=> Fixing page-aliases with more options to previous existing links (#1384)

modules/ROOT/pages/monitoring/metrics/reference.adoc
As it was decided to tag all new additions with the corresponding labels in the 5.x series, we have to label `database state metrics` with `Introduced in 5.7`.
See PR #636
=> Label db state metrics with 5.7

modules/ROOT/pages/monitoring/metrics/reference.adoc
Separate Bolt driver metrics from the Bolt metrics.
Fix names of the Bolt driver metrics according to the codebase.
For details, see https://github.com/neo-technology/neo4j/pull/22339. These metrics were added as a new metric class.
=> Fix names of the Bolt driver metrics

modules/ROOT/pages/monitoring/metrics/reference.adoc
As it was decided to tag all new additions with the corresponding labels in the 5.x series, we have to label `database state metrics` with `Introduced in 5.7`.
See PR #636
=> Label db state metrics with 5.7 (#1381)

modules/ROOT/pages/monitoring/metrics/reference.adoc
Separate Bolt driver metrics from the Bolt metrics. Fix names of the Bolt driver metrics according to the codebase. For details, see https://github.com/neo-technology/neo4j/pull/22339. These metrics were added as a new metric class.
---------
=> Fix names of the Bolt driver metrics (#1385)

modules/ROOT/pages/docker/introduction.adoc
In 5.17.0 we will start deprecating ubi8 images in favour of ubi9 ones. This updates the documentation so that we aren't telling users to start the deprecated images.
This should only be merged into the public documentation after the 5.17 release though, otherwise the docker commands won't work. I'm not sure what needs doing to ensure it doesn't get published early?
=> updated mentions of ubi8 docker images to ubi9

antora.yml, modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/configuration/dynamic-settings.adoc, modules/ROOT/pages/configuration/file-locations.adoc, modules/ROOT/pages/configuration/plugins.adoc, modules/ROOT/pages/docker/introduction.adoc, modules/ROOT/pages/monitoring/metrics/reference.adoc, modules/ROOT/pages/reference/procedures.adoc, modules/ROOT/pages/tools/cypher-shell.adoc, modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
Cherry-picked from #1357, #1365, #1380, #1383, #1403, #1426, #1429, #1433, and #1352.
=> Cherry-picks for 5.17

modules/ROOT/pages/configuration/configuration-settings.adoc
Fix the description of `dbms.memory.transaction.total.max`, where a "Defaults to" was missing compared to the in-code version.
=> Fix dbms.memory.transaction.total.max description

modules/ROOT/pages/tutorial/access-control.adoc
This was noticed in a recent internal pentest of RBAC.
We need to clarify that it is necessary to explicitly deny the ability to change your own privileges if you copy the admin role (otherwise the new role is essentially unconstrained).
=> Adding clarification that sub-admin roles should not be able to change their own privileges

modules/ROOT/pages/backup-restore/restore-backup.adoc
I removed the note but left the step 4. Do you think I should add the same step to the section **Restore a database backup**?
=> remove the note about dropping the database

modules/ROOT/pages/tutorial/access-control.adoc
Cherry-picked from #1440 
This was noticed in a recent internal pentest of RBAC.
We need to clarify that it is necessary to explicitly deny the ability to change your own privileges if you copy the admin role (otherwise the new role is essentially unconstrained).
=> Adding clarification that sub-admin roles should not be able to change their own privileges 

modules/ROOT/pages/authentication-authorization/limitations.adoc, modules/ROOT/pages/authentication-authorization/privileges-reads.adoc, modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
as well as notes on the relevant privileges linking to it
---------
Cherry-picked from #1453
=> Add section on limitations around privileges and missing labels (#1453)

modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Since we don't list anywhere the list of available store formats
(since these can change based on the version and edition of the DBMS),
we can point to our Store Formats documentation to allow users figure
out what are the options they could use there.
=> Add Store Format link to `--format` parameter entry

modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Since we don't list anywhere the list of available store formats (since these can change based on the version and edition of the DBMS), we can point to our Store Formats documentation to allow users figure out what are the options they could use there.
This is a cherry pick of #1486.
=> Cherrypick into 5.x: Add Store Format link to `--format` parameter entry

modules/ROOT/pages/authentication-authorization/sso-integration.adoc, modules/ROOT/pages/configuration/configuration-settings.adoc
We removed the `azp` claim check. Update the documentation to reflect this.
=> Remove azp checking from docs in line with OIDC spec update

modules/ROOT/pages/backup-restore/online-backup.adoc
DBMS-wide privileges do not get backed up when performing a database backup. This PR changes the docs entry of `neo4j-admin backup` to clarify this.
=> clarifying that DBMS privileges do not get backed up

modules/ROOT/pages/backup-restore/aggregate.adoc, modules/ROOT/pages/backup-restore/offline-backup.adoc, modules/ROOT/pages/backup-restore/online-backup.adoc, modules/ROOT/pages/backup-restore/planning.adoc, modules/ROOT/pages/backup-restore/restore-backup.adoc, modules/ROOT/pages/backup-restore/restore-dump.adoc, modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc, modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Added the 5.19 version info to the table texts. We could use version labels in suitable places instead.
=> S3 URI support for admin database import and database load/dump

modules/ROOT/pages/installation/linux/debian.adoc
Instead of saying "On Debian-based distributions, Neo4j is enabled to start automatically on system boot by default" It should say "On Debian-based distributions, users will need to run the following command to ensure that Neo4j starts automatically at boot time.:" with the code example 
sudo systemctl enable neo4j
=> Change "Starting the service automatically on system start" section and add code

modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
The example incorrectly includes an old release - the version is not needed as the image value in values.yaml should be the default
=> Update accessing-neo4j-ingress.adoc (#1552)

modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
The following line has a typo scv instead of svc
kubectl get scv -n ingress-nginx
should be
kubectl get svc -n ingress-nginx
or
kubectl get service -n ingress-nginx
=> Update accessing-neo4j-ingress.adoc (#1551)

modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
Some of the fields in SHOW DATABASES will always be null for databases that are not running. Update the documentation to reflect this.
=> Document SHOW DATABASES fields that can be NULL

modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
Change the `--array-delimiter` example to be set using the code point for the character `|` (the same used before, so we don't need to change the CSV content).
This was based on a user feedback, that it was not clear from the examples that they could have used (and how they could have used) unicode code points to set the delimiter to arbitrary characters, including non-printable ones.
See https://github.com/neo4j/neo4j/issues/13445.
=> Use unicode on CSV file delimiters example

modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
This is to avoid confusion, since we *don't* support passing the delimiter with the `0x` prefix.
=> Don't use `0x` prefix to reference the unicode code point

modules/ROOT/pages/installation/linux/rpm.adoc
=> Remove the note that Neo4j supports SELinux by default (#1629)

modules/ROOT/pages/installation/linux/rpm.adoc
=> Remove the note that Neo4j supports SELinux by default (#1627)

modules/ROOT/pages/configuration/index.adoc, modules/ROOT/pages/configuration/plugins.adoc
Add a footnote that GenAI plugin is available in EE only
Remove mentioning about the Ops Manager, as it doesn't run as a plugin but as a separate product
Mention the Configure plugins page in the intro page to the section
Clarify that Bloom Enterprise and GDS Enterprise require license key
=> Clarify a few details around Neo4j plugins

modules/ROOT/pages/configuration/index.adoc, modules/ROOT/pages/configuration/plugins.adoc
- Add a footnote that GenAI plugin is available in EE only 
- Remove mentioning about the Ops Manager, as it doesn't run as a plugin but as a separate product
- Mention the Configure plugins page in the intro page to the section 
- Clarify that Bloom Enterprise and GDS Enterprise require license key
---------
=> Clarify a few details around Neo4j plugins (#1636)

modules/ROOT/pages/database-administration/standard-databases/alter-databases.adoc, modules/ROOT/pages/database-administration/standard-databases/configuration-parameters.adoc, modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc, modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc, modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc, modules/ROOT/pages/database-administration/standard-databases/wait-options.adoc
This is a big PR and I think it would be better to merge it after 5.20 release.
- Syntax tables were added to the modified pages
- Pages were restructured in line with the neo4j-admin commands section
- Usage examples were aligned
=> Add `WAIT` examples to START/STOP sections and syntax tables to the Cypher adm commands

modules/ROOT/pages/authentication-authorization/manage-roles.adoc, modules/ROOT/pages/database-administration/standard-databases/alter-databases.adoc, modules/ROOT/pages/database-administration/standard-databases/configuration-parameters.adoc, modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc, modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc, modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc, modules/ROOT/pages/database-administration/standard-databases/wait-options.adoc, modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
- Syntax tables were added to the modified pages
- Pages were restructured in line with the neo4j-admin commands section
- Usage examples were aligned
---------
=> Add `WAIT` examples to START/STOP sections and syntax tables to the Cypher adm commands (#1615)

modules/ROOT/pages/monitoring/metrics/expose.adoc, modules/ROOT/pages/monitoring/metrics/reference.adoc
Add a note/tip to remind users that Neo4j metric names exposed via Prometheus are modified to comply with the Prometheus naming conventions. However, I don't think we have to provide a detailed example here because Prometheus is a third-party resource, and its standards or rules may change. IMO, it's enough to emphasize that the Prometheus metrics format is different from ours and to give a link to the Prometheus documentation.
=> Explain how neo4j metric names are transformed in Prometheus

modules/ROOT/pages/monitoring/metrics/expose.adoc, modules/ROOT/pages/monitoring/metrics/reference.adoc
Add a note/tip to remind users that Neo4j metric names exposed via Prometheus are modified to comply with the Prometheus naming conventions. However, I don't think we have to provide a detailed example here because Prometheus is a third-party resource, and its standards or rules may change. IMO, it's enough to emphasize that the Prometheus metrics format is different from ours and to give a link to the Prometheus documentation.
---------
=> Explain how neo4j metric names are transformed in Prometheus (#1658)

modules/ROOT/pages/monitoring/metrics/reference.adoc
I suppose this change is related to the [PR#25468](https://github.com/neo-technology/neo4j/pull/25468).
Should we add the label 'Introduced in 5.21'?
=> Add the metric `<prefix.>store.size.available_reserved`

modules/ROOT/pages/clustering/setup/encryption.adoc, modules/ROOT/pages/security/ssl-framework.adoc
Servers act as both servers and clients, and will complain if they only have one of the modes
=> Add a tip about needing server and client usage in intra-cluster TLS certificates

modules/ROOT/pages/kubernetes/operations/scaling.adoc
=> Enable server config should be true (#1695)

modules/ROOT/pages/configuration/configuration-settings.adoc
@yirensum additional context - https://neo4j.atlassian.net/wiki/spaces/Cluster/pages/511606802/Lighthouse+GA+plan
=> Added lighthouse public settings

modules/ROOT/pages/reference/procedures.adoc
@yirensum additional context - https://neo4j.atlassian.net/wiki/spaces/Cluster/pages/511606802/Lighthouse+GA+plan
=> Describe new lighthouse procedures

modules/ROOT/pages/tools/cypher-shell.adoc
Docs of https://github.com/neo-technology/neo4j/pull/26148.
=> Add --idle-timeout argument to cypher shell

modules/ROOT/pages/tools/neo4j-admin/push-to-cloud.adoc
=> Add a note that push to cloud does not support private linking

modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
Beginning in 5.19 you need to put the database name ahead of the named arguments. Otherwise, you get a File 'neo4j' doesn't exist error
Cherry-picked from #1689
=> Update neo4j-admin-import.adoc (#1689)

modules/ROOT/pages/configuration/configuration-settings.adoc
relates to https://github.com/neo-technology/neo4j/pull/26373
=> clarifying that `auth_cache_ttl` abd `use_ttl` applies to OIDC too

modules/ROOT/pages/configuration/configuration-settings.adoc
=> clarifying that `auth_cache_ttl` abd `use_ttl` applies to OIDC too (#1724)

modules/ROOT/pages/security/ssl-framework.adoc
it's a bit complicated to describe the table though, because the paragraph before makes it sound like all Neo4j versions except the ones listed use netty 4.1.11.
But the reality is that:
- 4.4.27 to 4.4.35 use netty 4.1.100.Final
- 4.4.24 to 4.4.26 use netty 4.1.94.Final
- 4.4.16 to 4.4.23 use netty 4.1.86.Final
- 4.4.10 to 4.4.15 use netty 4.1.86.Final
- etc
I'm not sure what the best way to describe that would be.
=> updated netty compatibility table for SSL usage

modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/database-administration/standard-databases/errors.adoc, modules/ROOT/pages/reference/procedures.adoc
In this PR, we want to add documentation for the following cluster procedures:
```
dbms.cluster.deallocateDatabaseFromServer(server, database, dryrun)
dbms.cluster.deallocateNumberOfDatabases(server, number, dryrun)
dbms.cluster.deallocateDatabaseFromServers(servers, database, dryrun)
dbms.cluster.reallocateDatabase(database, dryrun)
dbms.cluster.reallocateNumberOfDatabases(number, dryrun)
```
We also add some scenarios in which a user might use these new procedures for
=> Adding new limited allocation procedures

modules/ROOT/pages/clustering/databases.adoc
If there are lots of databases to move, an unbounded REALLOCATE can be stressful for the cluster and the databases involved. With the newly public limited reallocate procedures, they provide a gentler way to achieve the balancing incrementally.
=> Add a caution about REALLOCATE DATABASES moving too much

modules/ROOT/pages/authentication-authorization/load-privileges.adoc
adds a warning against allowing insecure protocols for `LOAD CSV`
this PR is the operations manual copy of the [cypher manual equivalent](https://github.com/neo4j/docs-cypher/pull/1006)
=> adding health warning about insecure protocols for LOAD CSV

modules/ROOT/pages/database-administration/standard-databases/alter-databases.adoc, modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Copy the PRs: https://github.com/neo4j/docs-operations/pull/1770 and https://github.com/neo4j/docs-operations/pull/1771.
=> Change  txLogEnrichment mode from `NONE` to `OFF`

modules/ROOT/pages/monitoring/logging.adoc
Remove the configuration setting from the table as it was removed in 5.0 (see [PR#16649](https://github.com/neo-technology/neo4j/pull/16649))
=> Remove the config `db.logs.query.time_logging_enabled`

modules/ROOT/pages/monitoring/logging.adoc
Remove the configuration setting from the table as it was removed in 5.0 (see [PR#16649](https://github.com/neo-technology/neo4j/pull/16649))
=> Remove the config `db.logs.query.time_logging_enabled` (#1773)

modules/ROOT/pages/security/ssl-framework.adoc
=> Netty and tcnative files are included in the /lib directory from v5.21 (#1801)

modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
These instructions were added in [the PR#906](https://github.com/neo4j/docs-operations/pull/906).
=> Improve a few steps configuring SSO on Azure

modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
These instructions were added in [the
PR#906](https://github.com/neo4j/docs-operations/pull/906).
---------
=> Improve a few steps configuring SSO on Azure (#1767)

modules/ROOT/pages/clustering/setup/deploy.adoc
Recent question in slack pointed out that we describe how to set up a 3 cluster (as that should be the normal), but we don't mention anywhere that in case of a 2 member cluster an extra setting is needed.
=> Add a note about clusters with 2 members

modules/ROOT/pages/clustering/setup/deploy.adoc
Recent question in slack pointed out that we describe how to set up a 3 cluster (as that should be the normal), but we don't mention anywhere that in case of a 2 member cluster an extra setting is needed.
---------
=> Add a note about clusters with 2 members (#1815)

modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
add [role=label--new-5.21] version label to property rules
=> add version label to property rules

modules/ROOT/pages/backup-restore/online-backup.adoc
This support case shows how a customer is misled by absolute description of backup being faster when compression is disabled.
https://trello.com/c/xsCLZrwy/7747-s3dbs-risk-management5181-backup-is-taking-more-time-with-compressfalse
=> Added detail on backup compression flag

modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc, modules/ROOT/pages/database-administration/composite-databases/delete-composite-databases.adoc, modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc, modules/ROOT/pages/database-administration/syntax.adoc
to drop any aliases blocking the deletion of the database
Documenting https://github.com/neo-technology/neo4j/pull/26465, ~~needs to wait until that has been merged.~~
=> Add `DROP DATABASE name CASCADE ALIASES`

modules/ROOT/content-nav.adoc, modules/ROOT/pages/clustering/monitoring/status-check.adoc
As part of the 2DC support, we needed to make the rafted status check procedure public. And therefore, we also need to add a public documentation. I've kept it quite simple. But it may be too technical in some parts, let me know.
P.S It's required to be part of the 5.24 release.
=> Docs for the rafted status check procedure.

modules/ROOT/pages/clustering/index.adoc, modules/ROOT/pages/clustering/monitoring/status-check.adoc
Minor improvements to the status check page, mainly aligning the formatting closer to the other monitoring pages:
- Using tables for the arguments and return values 
- Change title to 'Monitor replication status'
- Add an example of sample output
=> Edit status check (#1836)

modules/ROOT/content-nav.adoc, modules/ROOT/pages/configuration/file-locations.adoc, modules/ROOT/pages/docker/introduction.adoc, modules/ROOT/pages/security/ssl-fips-compatibility.adoc, modules/ROOT/pages/security/ssl-framework.adoc
I cleaned up the existing SSL documentation and added a new page about how to configure SSL to be FIPS compatible.
---------
=> New SSL instructions for FIPS compatibility (#1806)

modules/ROOT/pages/authentication-authorization/manage-privileges.adoc, modules/ROOT/pages/authentication-authorization/manage-roles.adoc
Update the column information to not just be in the text but as proper tables for the 2 show commands that didn't have them as tables already.
=> Show columns clarifications

modules/ROOT/pages/security/ssl-fips-compatibility.adoc
the FIPS  features had to be rolled back from the docker image, so we need to remove that section of the documentation for now. It will return once the docker image name is finalised so I only commented out the relevant bits.
=> disabled section in ssl-fips page about docker image until docker image is finalised

modules/ROOT/pages/security/ssl-fips-compatibility.adoc
the FIPS features had to be rolled back from the docker image, so we need to remove that section of the documentation for now. It will return once the docker image name is finalised so I only commented out the relevant bits.
=> disabled section in ssl-fips page about docker image until docker image is finalised (#1848)

modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Replace with new option `existingDataSeedServer`
Documenting https://github.com/neo-technology/neo4j/pull/27123
=> Deprecate `existingDataSeedInstance` option to CREATE DATABASE

modules/ROOT/pages/backup-restore/aggregate.adoc, modules/ROOT/pages/backup-restore/offline-backup.adoc, modules/ROOT/pages/backup-restore/online-backup.adoc, modules/ROOT/pages/backup-restore/restore-backup.adoc, modules/ROOT/pages/backup-restore/restore-dump.adoc, modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
see https://github.com/neo-technology/neo4j/pull/27466, https://github.com/neo-technology/neo4j/pull/27502, and https://github.com/neo-technology/neo4j/pull/27550
=> Update the options' descriptions of the neo4j-admin commands according to the code

modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
We think it probably works, we just haven't tested it. So let's not say one way or the other just yet.
Cherry-picked from #1866
=> Removed message about no TLS/SSL support for Minio. (#1866)

modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
as per ticket https://trello.com/c/uUkM9CM5/350-document-change-console-drag-and-drop-import-to-support-version-44-or-above
=> remove before version 4.4

modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
as per ticket
https://trello.com/c/uUkM9CM5/350-document-change-console-drag-and-drop-import-to-support-version-44-or-above
=> remove before version 4.4 (#1862)

modules/ROOT/pages/database-internals/concurrent-data-access.adoc, modules/ROOT/pages/database-internals/store-formats.adoc, modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Cypher Manual PR: https://github.com/neo4j/docs-cypher/pull/1041
=> Update constraints link following restructure in Cypher Manual

modules/ROOT/pages/performance/memory-configuration.adoc
=> Update documentation to include recommendations for SWAP (#1883)

modules/ROOT/pages/backup-restore/online-backup.adoc, modules/ROOT/pages/clustering/setup/encryption.adoc, modules/ROOT/pages/security/ssl-framework.adoc
=> Improve the documentation around the use of ciphers (#1895)

modules/ROOT/pages/monitoring/logging.adoc
[Trello card](https://trello.com/c/e1PTFRXS/469-logging-of-databasename-for-securitylog-is-not-for-all-events#)
=> Add clarification that database field depends on the security event

modules/ROOT/pages/monitoring/logging.adoc
Cherry-picked from #1904 
[Trello
card](https://trello.com/c/e1PTFRXS/469-logging-of-databasename-for-securitylog-is-not-for-all-events#)
=> Add clarification that database field depends on the security event (#1904)

modules/ROOT/pages/docker/docker-compose-standalone.adoc
=> Update the example key-value pair to use / instead of : (#1914)

modules/ROOT/content-nav.adoc, modules/ROOT/pages/docker/clustering.adoc, modules/ROOT/pages/docker/configuration.adoc, modules/ROOT/pages/docker/docker-compose-standalone.adoc, modules/ROOT/pages/docker/index.adoc, modules/ROOT/pages/docker/introduction.adoc, modules/ROOT/pages/docker/mounting-volumes.adoc, modules/ROOT/pages/docker/operations.adoc, modules/ROOT/pages/docker/plugins.adoc
https://trello.com/c/MgmtbjRJ/1470-support-docker-secrets
* Adds documentation for general docker compose usage
* Adds documentation for using secrets with neo4j
---------
Cherry-picked from #1804 
* Add documentation for persistent volumes as in 5.x
* Add documentation for plugins as in 5.x
=> Add missing content to the Docker docs (#1804)

modules/ROOT/pages/docker/docker-compose-standalone.adoc
[Trello](https://trello.com/c/nlvbN50T/540-change-the-docker-secrets-feature-to-limit-the-usage-of-env-vars-that-are-prefixed-with-neo4j?filter=*)
=> Docker secrets should only support neo4j variables

modules/ROOT/pages/docker/docker-compose-standalone.adoc
[Trello](https://trello.com/c/nlvbN50T/540-change-the-docker-secrets-feature-to-limit-the-usage-of-env-vars-that-are-prefixed-with-neo4j?filter=*)
Cherry-picked from #1917
=> Docker secrets should only support neo4j variables (#1917)

antora.yml
Reverts neo4j/docs-operations#1920
Wrong branch, should be 5.x
=> Revert "Fix neo4j-version-exact"

modules/ROOT/pages/authentication-authorization/built-in-roles.adoc, modules/ROOT/pages/authentication-authorization/database-administration.adoc, modules/ROOT/pages/authentication-authorization/dbms-administration.adoc, modules/ROOT/pages/authentication-authorization/limitations.adoc, modules/ROOT/pages/authentication-authorization/load-privileges.adoc, modules/ROOT/pages/authentication-authorization/manage-privileges.adoc, modules/ROOT/pages/authentication-authorization/manage-roles.adoc, modules/ROOT/pages/authentication-authorization/privileges-reads.adoc, modules/ROOT/pages/authentication-authorization/privileges-writes.adoc, modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc, modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc, modules/ROOT/pages/database-administration/aliases/naming-aliases.adoc
=> Change aura-db-enterprise to aura-db-business-critical aura-db-dedicated (#1912)

modules/ROOT/pages/clustering/databases.adoc
* S3SeedProvider is deprecated as of 5.26
* FileSeedProvider added in 5.26
* file: is deprecated for URLConnectionProvider as of 5.26
* Reorder providers putting S3SeedProvider last
=> Add deprecations and FileSeedProvider

modules/ROOT/pages/clustering/setup/discovery.adoc, modules/ROOT/pages/reference/procedures.adoc
Before publishing the docs the internal prefix from the procedure path needs to be removed
=> Describe the semi-automated procedure that migrates Discovery Service V1 to V2.

modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/clustering/servers.adoc
Document this change: https://github.com/neo-technology/neo4j/pull/27665
=> Allow parameters in CREATE/ALTER DATABASE TOPOLOGY

modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
cypher manual [PR](https://github.com/neo4j/docs-cypher/pull/1070)
=> Example of property-based access control using temporal value

modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Also add a note about deprecated store formats
We may need to add some more details about the deprecations once clustering get to look at it. 
Depends on: https://github.com/neo4j/docs-operations/pull/1909
=> Deprecate `seedConfig`, and `seedCredentials`

modules/ROOT/pages/configuration/configuration-settings.adoc
related to:
- https://github.com/neo-technology/neo4j/pull/27220
- https://github.com/neo-technology/neo4j/pull/27762
- https://github.com/neo-technology/neo4j/pull/27695
=> Update config settings

modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
We are no longer deprecating seedConfig in LTS
=> Remove deprecation for seedConfig

modules/ROOT/pages/configuration/configuration-settings.adoc
Related to https://github.com/neo-technology/neo4j/pull/27660, https://github.com/neo-technology/neo4j/pull/27785, and https://github.com/neo-technology/neo4j/pull/27962.
These are implemented in 5.26
=> Update `server.metrics.filter`, add new 5.26 configuration settings 

modules/ROOT/pages/monitoring/metrics/reference.adoc
see https://github.com/neo-technology/neo4j/commit/758960863da689d7b47d6562037e4bd4ea4259cb#diff-824ff32f02805ec284d529daf30fe070bcd5f58a3c7be32bced227fa75c43c7b
=> Add an MVCC related metric

modules/ROOT/pages/authentication-authorization/dbms-administration.adoc, modules/ROOT/pages/backup-restore/copy-database.adoc, modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc, modules/ROOT/pages/database-administration/aliases/naming-aliases.adoc, modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
This is the only mention of escaping with backticks that I found in the Operations manual.
Cypher Manual PR: https://github.com/neo4j/docs-cypher/pull/1111
=> Using quoting instead of escaping with backticks

modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
The Parquet file support for neo4j admin import will come out in on of the next minor versions as a preview feature.
Depending on the feedback we get from customers and users, there will be definitely coming more (also to the docs).
This is a quite defensive change to avoid promising too much but also pointing out that this feature exists at all ;)
Because the feature itself is not merged yet, I added the DO NOT MERGE label.
Please let us get this into a shape where we can just merge it after the feature went into the product, thanks.
This supersedes https://github.com/neo4j/docs-operations/pull/1850
=>  Add neo4j-admin-import section and parameter details for Parquet.

modules/ROOT/pages/kubernetes/operations/dump-load.adoc
without extra flag got:
```
Failed to load database 'system': Database already exists: systemLoad failed for databases: 'system'
Load failed for databases: 'system'
```
=> fix load command example

modules/ROOT/pages/kubernetes/operations/dump-load.adoc
Cherry-picked from #1967 
without extra flag got:
```
Failed to load database 'system': Database already exists: systemLoad failed for databases: 'system'
Load failed for databases: 'system'
```
=> fix load command example (#1967)

modules/ROOT/pages/monitoring/logging.adoc
In order to know which database the query is targeting, we do some parsing to find if there is a USE-clause (e.g.  `USE db RETURN 1 AS result`).  If the parsing fails, we are not able to figure out what database the query should be run at and therefor the field in the log will be <none>. 
Please let me know if I can improve the documentation with more details, I just don't want to put information to confuse the user even more.
=> add note about database name in query log

modules/ROOT/pages/configuration/configuration-settings.adoc
Small fix to render the deprecation label for the `dbms.cluster.discovery.type` config
=> Fix the deprecation label for `dbms.cluster.discovery.type` (#1986)

modules/ROOT/pages/monitoring/logging.adoc
=> Update the note about the default GQLSTATUS code 50N42 (#1992)

modules/ROOT/pages/database-internals/checkpointing.adoc, modules/ROOT/pages/database-internals/index.adoc, modules/ROOT/pages/database-internals/store-formats.adoc, modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
The _Database internals_ section was created in 5.x. This means we don't have anything similar in the v4.4 docs.
Some of the pages can be linked to the Java Reference 4.4 and its section _Transaction management_.
=> Tie up the Database internals section with the v4.4 (#1973)

modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
We have relaxed the database naming rules to allow a database name to start with a digit. Update docs to reflect this.
See also https://github.com/neo-technology/neo4j/pull/28262
=> Allow database names to start with a digit

modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
Document what changed here: https://github.com/neo-technology/neo4j/pull/27074
=> Disallow unquoted database names with dot

modules/ROOT/pages/configuration/configuration-settings.adoc
Gzip was removed from the list of supported compression algorithms.
=> Remove GZip compression

modules/ROOT/pages/configuration/configuration-settings.adoc
Also complete the change from 'DBMS panic' to 'server panic', which is a more accurate term.
Related to https://github.com/neo-technology/neo4j/pull/28210
=> Change default for shutdown on panic setting

modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
Cherry-picks: https://github.com/neo4j/docs-operations/pull/2010
=> Prefer seed from uri

modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/clustering/disaster-recovery.adoc
This PR rewrites the disaster recovery docs based on the new recreate and status check procedures. 
With regards to the functional changes there are three major things to note. 
1. The recovery of the system database is the same as before, even though the way we check if the system db is write available or not has changed. 
2. The step which removes lost servers now also includes recreating some databases. It was decided this mixing of recovering servers and databases is necessary to get recreate into the guide in the best way we could see. 
3. Previously it was not clear how to handle quarantined databases, even though the guide mentioned them in the intro. Now, it is more explicitly discussed how they are supposed to be handles during disaster recovery.
In the past, we have also gotten …
=> Rewrite disaster recovery based on recreate and status check

modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/clustering/disaster-recovery.adoc
This PR rewrites the disaster recovery docs based on the new recreate and status check procedures.
With regards to the functional changes there are three major things to note.
1. The recovery of the system database is the same as before, even though the way we check if the system db is write available or not has changed.
2. The step which removes lost servers now also includes recreating some databases. It was decided this mixing of recovering servers and databases is necessary to get recreate into the guide in the best way we could see.
3. Previously it was not clear how to handle quarantined databases, even though the guide mentioned them in the intro. Now, it is more explicitly discussed how they are supposed to be handles during disaster recovery.
In the past, we have also gotten …
=> Rewrite disaster recovery based on recreate and status check (#1890)

modules/ROOT/pages/database-administration/standard-databases/errors.adoc, modules/ROOT/pages/procedures.adoc
Added docs for brand-new `unquarantineDatabase` procedure and for the now deprecated `quarantineDatabase` procedure.
=> Add new unquarantine procedure + deprecate quarantine

modules/ROOT/pages/clustering/monitoring/status-check.adoc, modules/ROOT/pages/procedures.adoc
Related to https://github.com/neo-technology/neo4j/pull/28664
The description is copy-pasted from this other docs page: https://github.com/neo4j/docs-operations/blob/dev/modules/ROOT/pages/clustering/monitoring/status-check.adoc?plain=1
=> Add description to fields in RaftedStatusCheck procedure

modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
Reverts neo4j/docs-operations#1948
Cypher 25 will not be released with 2025.01. I'll create a separate PR with this feature.
=> Revert "Disallow unquoted database names with dot"

modules/ROOT/pages/docker/plugins.adoc
Old output was out of date and could have  been misleading
=> updated example output from an incorrect plugin request.

modules/ROOT/pages/monitoring/metrics/reference.adoc
Adding metrics for Raft Snapshot download. See https://github.com/neo-technology/neo4j/pull/28148
=> Add metrics for Raft Snapshots. Attempt/success/fail

modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/docker/ref-settings.adoc
This was replaced by dbms.max_databases in 5.6.
=> Remove deprecated and migrated server.max_databases setting

modules/ROOT/pages/monitoring/metrics/reference.adoc
The Raft core metrics and Read replica metrics were old names from 4.x, supported during 5.x. They have been removed in 2025.01
=> Remove deprecated and removed Cluster metrics

modules/ROOT/pages/docker/plugins.adoc
Old output was out of date and could have  been misleading
Cherry-picked from #2040
=> updated example output from an incorrect plugin request. (#2040)

modules/ROOT/pages/procedures.adoc
The title says it all: we didn't have description for the fields of the `recreateDatabase` procedure 🙈 
The related monorepo PR is https://github.com/neo-technology/neo4j/pull/28960
=> Add description for the fields of recreateDatabase procedure

modules/ROOT/pages/monitoring/metrics/reference.adoc
The corresponding PRs are https://github.com/neo-technology/neo4j/pull/28128 and https://github.com/neo-technology/neo4j/pull/28439/files
=> Add CPU usage metrics

modules/ROOT/pages/procedures.adoc
see https://github.com/neo-technology/neo4j/pull/28933
=> Remove `dbms.setDatabaseAllocator()`

modules/ROOT/pages/monitoring/metrics/reference.adoc
see https://github.com/neo-technology/neo4j/pull/23089
=> Replace `<prefix>.store.size.total` with `<prefix>.store.size.full`

modules/ROOT/pages/clustering/databases.adoc
- Remove 5.x specific documentation from 'Seed from URI' section
- Add section on `seedRestoreUntil` option
=> Add seed restore until section and remove 5.x seed provider info

modules/ROOT/pages/installation/linux/debian.adoc, modules/ROOT/pages/installation/linux/rpm.adoc
key differences:
* must download from `{neo4j-version}` not `latest` now.
* no need for annoying oracle jdk workaround in redhat/fedora. Oracle seem to have fixed that bug in multiple java versions :woman_shrugging: 
dev PR is https://github.com/neo4j/docs-operations/pull/2054
=> updated 5.26 linux install instructions to move the repository links

modules/ROOT/pages/installation/linux/debian.adoc, modules/ROOT/pages/installation/linux/rpm.adoc
Key differences:
* java 21 not java 17
* must download from `latest` not `{neo4j-version}` or anything
* no need for annoying oracle jdk workaround in redhat/fedora.
I will do a separate PR for 5x to remove references to downloading stuff from `latest`.
=> updated install instructions for jdk 21 and new apt/dnf repository branches

modules/ROOT/pages/clustering/setup/discovery.adoc
This PR is related to https://github.com/neo4j/docs-operations/pull/2016.
=> Clarify that you have to list system primaries in your endpoints

modules/ROOT/pages/backup-restore/online-backup.adoc, modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/clustering/setup/discovery.adoc, modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/configuration/dynamic-settings.adoc, modules/ROOT/pages/docker/ref-settings.adoc, modules/ROOT/pages/tools/neo4j-admin/migrate-configuration.adoc
Update configuration settings across all pages
=> Update configuration settings for 2025.01

modules/ROOT/pages/monitoring/logging.adoc
Hi @henriknyman, it seems that those two log entries were missing in the docs. Could you please take a look to see if I have documented them correctly? Also, in which version have they been introduced? Thanks a lot!
=> Document executionPlanCacheKeyHash and executableQueryCacheHit

modules/ROOT/pages/authentication-authorization/built-in-roles.adoc, modules/ROOT/pages/authentication-authorization/dbms-administration.adoc, modules/ROOT/pages/authentication-authorization/limitations.adoc, modules/ROOT/pages/authentication-authorization/load-privileges.adoc, modules/ROOT/pages/authentication-authorization/privileges-writes.adoc, modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc, modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/clustering/setup/routing.adoc, modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/configuration/file-locations.adoc, modules/ROOT/pages/configuration/plugins.adoc, modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc, modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc, modules/ROOT/pages/database-administration/aliases/naming-aliases.adoc, modules/ROOT/pages/database-administration/aliases/remote-database-alias-configuration.adoc, modules/ROOT/pages/database-administration/composite-databases/querying-composite-databases.adoc, modules/ROOT/pages/database-administration/routing-decisions.adoc, modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc, modules/ROOT/pages/database-internals/concurrent-data-access.adoc, modules/ROOT/pages/database-internals/transaction-management.adoc, modules/ROOT/pages/introduction.adoc, modules/ROOT/pages/monitoring/query-management.adoc, modules/ROOT/pages/performance/index-configuration.adoc, modules/ROOT/pages/performance/memory-configuration.adoc, modules/ROOT/pages/performance/statistics-execution-plans.adoc, modules/ROOT/pages/procedures.adoc, modules/ROOT/pages/security/checklist.adoc, modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
The page-version attribute between the 2 manuals will no longer match once 2025.01 is released
=> Fix links to Cypher Manual

modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
=> 5.x backup support generic s3 endpoints

modules/ROOT/pages/authentication-authorization/index.adoc, modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/configuration/ports.adoc, modules/ROOT/pages/docker/security.adoc, modules/ROOT/pages/security/checklist.adoc, modules/ROOT/pages/security/ssl-framework.adoc
=> Update Netty-TCNative for 2025.01 and other updates

modules/ROOT/pages/backup-restore/copy-database.adoc, modules/ROOT/pages/changes-deprecations-removals.adoc, modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Document changes for the 2025.01 release:
* new option of the copy command
* new option of the incremental import command
The `neo4j-admin database restore` command will be updated in the 2025.02 release.
=> Add missing options of the copy and incremental import commands

modules/ROOT/pages/clustering/setup/discovery.adoc
This is to highlight the port change for discovery v2. I don't think this is needed in v2025 because users should be using Lighthouse by then.
=> Discovery v2 - hightlight port change

antora.yml, modules/ROOT/pages/index.adoc, publish.yml
This PR updates the component descriptor (_antora.yml_) to mark 5.26 as LTS.
To do this, we add `lts: true`. By also setting `display_version: 5.26` we can keep the current URL structure (_/5/_) but at the same time we can be explicit about the minor version that the _/5/_ docs apply to. 
This PR can be merged after 2025.01 is released.
=> Update Antora files for LTS

modules/ROOT/pages/authentication-authorization/manage-privileges.adoc, modules/ROOT/pages/authentication-authorization/privileges-reads.adoc, modules/ROOT/pages/authentication-authorization/privileges-writes.adoc, modules/ROOT/pages/database-administration/syntax.adoc
=> Add links to the Components of the graph privilege commands from where HOME GRAPH is mentioned (#2102)

modules/ROOT/pages/performance/bolt-thread-pool-configuration.adoc
=> Fix the Configure the thread pool for a Bolt connector example to show minimum size 5 as it is in the description (#2103)

modules/ROOT/pages/clustering/databases.adoc
Improve the formatting on the page _Manage db in cluster_. Based on the PR #2124
=> Turn 5th level headings into the descr list

modules/ROOT/pages/procedures.adoc
These functions  are supported, as they have been adopted by customers in production.
=> Removed beta label from set vector property functions.

modules/ROOT/pages/procedures.adoc
These functions are supported, as they have been adopted by customers in production.
=> Removed beta label from set vector property functions. (#2137)

modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Depends on https://github.com/neo-technology/neo4j/pull/29508/files
=> Improve the descriptions of --skip-bad-relationships, --skip-duplicate-nodes, and --update-all-matching-relationships

modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Docs addition for admin import.
The feature will be get merged into the dev branch today.
=> Add section about Parquet header in admin import.

modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
You may need to preserve the database structure (indexes and constraints) when you move the database from test env to production. In this case, it's important to know that the `CREATE OR REPLACE DB` cmd removes not only data but also indexes and constraints. If you want to keep them, you have to do it before executing the command.
=> Clarify that CREATE OR REPLACE DB deletes indexes and constraints as well

modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
You may need to preserve the database structure (indexes and constraints) when you move the database from test env to production. In this case, it's important to know that the `CREATE OR REPLACE DB` cmd removes not only data but also indexes and constraints. If you want to keep them, you have to do it before executing the command.
=> Clarify that CREATE OR REPLACE DB deletes indexes and constraints as well (#2154)

modules/ROOT/pages/monitoring/logging.adoc
related to https://github.com/neo-technology/neo4j/pull/28252
=> Add info about the `queryLang` field

modules/ROOT/pages/backup-restore/offline-backup.adoc, modules/ROOT/pages/backup-restore/planning.adoc, modules/ROOT/pages/backup-restore/restore-dump.adoc
=> Update dump/load that for CE you must stop the whole DBMS (#2168)

modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
=> Document update/change/delete in block format incremental import (#2177)

modules/ROOT/pages/configuration/configuration-settings.adoc, modules/ROOT/pages/procedures.adoc, modules/ROOT/pages/security/ssl-framework.adoc
https://trello.com/c/4hpH8ouM/429-dynamic-tls-certificates-with-online-rotation
=> Documentation for TLS certificate rotation feature

modules/ROOT/pages/clustering/disaster-recovery.adoc
Remove ambiguity that disaster recovery can recover a write unavailable database without causing read unavailability.
=> Clarify that a recreate won't keep read availability.

modules/ROOT/pages/clustering/disaster-recovery.adoc
Remove ambiguity that disaster recovery can recover a write unavailable database without causing read unavailability.
=> Clarify that a recreate won't keep read availability. (#2186)

modules/ROOT/pages/clustering/databases.adoc
=> Fix the cloud URIs

modules/ROOT/pages/security/ssl-framework.adoc
Clarify steps, fix formatting and mistakes.
=> Clarify the difference between copying and overwriting TLS certificates

modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
To make the page consistent with other pages.
---------
=> Turn examples into sections (#2201)

modules/ROOT/pages/authentication-authorization/database-administration.adoc, modules/ROOT/pages/authentication-authorization/manage-privileges.adoc, modules/ROOT/pages/authentication-authorization/manage-roles.adoc
Not sure this is the right way to do it, mention Cypher 25 in the operations manual, or is there a way to specify which cypher version to see documentation for?
=> Update REVOKE information to say that in cypher 25 you get errors for impossible revoke commands

modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
* Explain how existing store files work, this has never really been well documented
* Add a different set of options for Cypher 25
* WAIT is different in Cypher 25.
This is an initial attempt at documenting these changes in Cypher 25, would be good to get some feedback from the docs team on the approach.
=> Updates to CREATE DATABASE for Cypher 25

modules/ROOT/pages/installation/linux/rpm.adoc
=> Split the code block

modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
We updated the store column to not say `--0.0` in 2025.04 (and backported to next release of 5.LTS as well), and the currentPrimariesCount/currentSecondariesCount to be null to match what the requested versions already did.
Also added the sentence about being null for composite on the columns where that was already the case.
=> Update column info for show databases to mention where composite databases return null

modules/ROOT/pages/changes-deprecations-removals.adoc, modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/import.adoc, modules/ROOT/pages/procedures.adoc
In 2025.04 we deprecate `dbms.cluster.recreateDatabase` in favour of `dbms.recreateDatabase`.
=> Deprecate `dbms.cluster.recreateDatabase`

modules/ROOT/pages/changes-deprecations-removals.adoc, modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/import.adoc, modules/ROOT/pages/procedures.adoc
In 2025.04 we deprecate `dbms.cluster.recreateDatabase` in favour of `dbms.recreateDatabase`.
---------
=> Deprecate `dbms.cluster.recreateDatabase` (#2210)

modules/ROOT/pages/tutorial/index.adoc, modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
=> Update Okta examples (#2185)

modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Cherry-picked from #2233 
when any groups and roles are explicitly given
=> Add a note about the automatic group_to_role_mapping being disabled (#2233)

modules/ROOT/pages/authentication-authorization/limitations.adoc, modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
This PR handles the Deprecations, additions, and compatibility page. https://github.com/neo4j/docs-cypher/pull/1239
=> Relationship PBAC

modules/ROOT/pages/import.adoc
=> Document --temp-path for import (#2262)

modules/ROOT/pages/cypher-shell.adoc
=> Document --error-format argument to Cypher Shell (#2267)

modules/ROOT/pages/database-internals/transaction-management.adoc
This is true since Neo4j 5.13.
=> Custom tx timeout can be set to any value

modules/ROOT/pages/database-internals/transaction-management.adoc
This is true since Neo4j 5.13.
---------
=> Custom tx timeout can be set to any value (#2282)

modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/2292
=> Add tempDir to the aggregate command in K8s (#2292)

modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
This all started with me using this feature and noticing that the documented examples triggered a warning.
Digging further into the feature and thus the docs, I took the chance to polish examples (syntax highlighting, avoid scrolling) and a few wordings.
=> Remove `useExisting` option; polish examples & page

modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
Spinoff of #2287 , on the `cypher-25` base branch as the option is deprecated then.
=>  Remove `useExisting` option; polish examples & page

modules/ROOT/pages/changes-deprecations-removals.adoc, modules/ROOT/pages/configuration/configuration-settings.adoc
based on https://github.com/neo-technology/neo4j/pull/30553
=> Document `server.backup.advertised_address` and deprecate `dbms.routing.load_balancing.plugin`

modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
Removing `a` in the table header (see line 44 in the PR #2212) led to the formatting issues: lists and code blocks are not rendered as they should be.
This PR fixes those issues
=> Fix formatting of the listing db output

modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
Removing `a` in the table header (see line 44 in the PR #2212) led to the formatting issues: lists and code blocks are not rendered as they should be.
This PR fixes those issues
=> Fix formatting of the listing db output (#2339)

modules/ROOT/pages/changes-deprecations-removals.adoc
A similar one https://github.com/neo4j/docs-status-codes/pull/313
=> Error messages are deprecated (#2330)

modules/ROOT/pages/monitoring/causal-cluster/http-endpoints.adoc
=> Clarify database health status

modules/ROOT/content-nav.adoc, modules/ROOT/pages/changes-deprecations-removals.adoc, modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/clustering/disaster-recovery.adoc, modules/ROOT/pages/database-administration/standard-databases/recreate-database.adoc, modules/ROOT/pages/import.adoc, modules/ROOT/pages/procedures.adoc
Since the recreate procedure is not specific to clustering, it is logical to move this content to a separate page under the _Database administration_ section.
---------
=> Move the recreate procedure to a separate page (#2367)

modules/ROOT/pages/backup-restore/restore-backup.adoc, modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
When Cypher 25 is released, we'll continue to show query examples for Cypher 5.
When PR #2368 is merged, this one needs to be updated
=> Fix Cypher examples to show its both versions

modules/ROOT/pages/import.adoc
Clarify that CSV imports empty lists as null whereas Parquet handles empty as empty.
=> Explain list handling differences between Parquet and CSV

modules/ROOT/content-nav.adoc, modules/ROOT/pages/clustering/databases.adoc, modules/ROOT/pages/clustering/disaster-recovery.adoc, modules/ROOT/pages/database-administration/standard-databases/recreate-database.adoc, modules/ROOT/pages/procedures.adoc
The recreate procedure in the 5.x version can also be applied to a standalone database. Therefore, we need to move it to a separate page under the _Database administration_ section, as it has already been done in the current docs (see the `main` branch). See PR #2367.
=> Move the recreate procedure to the separate page in 5.x

modules/ROOT/pages/changes-deprecations-removals.adoc
=> Update deprecations and removals for the June release

modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc, modules/ROOT/pages/configuration/configuration-settings.adoc
We state that the _Configuration settings_ page lists all config settings in Neo4j. But we miss
`dbms.routing.load_balancing.config.server_policies`, which is not a setting but a setting group. Nevertheless, we need to include this setting group/plugin on the page.
=> Add `dbms.routing.load_balancing.config.server_policies` to the configs reference page (#2414)

modules/ROOT/pages/configuration/configuration-settings.adoc
=> Add `causal_clustering.load_balancing.config.server_policies` to the ref page

modules/ROOT/pages/import.adoc
Unsure if this should be inline with the header or appear after the header.
Searched the repository for comparable situations but haven't found any.
Both looks ... both have their pros and cons ;)
=> Clarify version for parquet header support.

modules/ROOT/pages/kubernetes/accessing-neo4j.adoc, modules/ROOT/pages/kubernetes/configuration.adoc
=> Remove externalService and add services.neo4j.spec.loadBalancerIP (#2494)

modules/ROOT/pages/import.adoc
The Operations manual covers all releases of 2025.xx series. That's why we cannot simply replace examples with new ones, as new functionality has been added. We also need to retain examples for earlier versions of Neo4j.
=> Add tabbed examples for multiple node IDs

modules/ROOT/pages/authentication-authorization/built-in-roles.adoc, modules/ROOT/pages/introduction.adoc, modules/ROOT/pages/monitoring/metrics/essential.adoc, modules/ROOT/pages/performance/index-configuration.adoc, modules/ROOT/pages/procedures.adoc
To update the links to the Cypher manual following the renaming of several pages.
=> Fix broken links

modules/ROOT/pages/tools/neo4j-admin/unbind.adoc
Since 5.0 you cannot use `unbind` to turn a cluster member into a standalone server.
---------
=> Remove problematic part from `unbind` docs (#2570)

modules/ROOT/pages/backup-restore/consistency-checker.adoc, modules/ROOT/pages/clustering/unbind.adoc, modules/ROOT/pages/configuration/migrate-configuration.adoc, modules/ROOT/pages/configuration/neo4j-admin-memrec.adoc, modules/ROOT/pages/configuration/validate-config.adoc, modules/ROOT/pages/cypher-shell.adoc, modules/ROOT/pages/database-administration/standard-databases/migrate-database.adoc, modules/ROOT/pages/database-internals/neo4j-admin-store-info.adoc, modules/ROOT/pages/import.adoc, modules/ROOT/pages/neo4j-admin-neo4j-cli.adoc
This PR repeats the PR #2290, except for the following two pages:
* modules/ROOT/pages/monitoring/neo4j-admin-report.adoc *
modules/ROOT/pages/database-administration/standard-databases/upload-to-aura.adoc. They have necessary `page-aliases`.
=> Restore page-aliases for the pages on neo4j-admin cmds (#2600)

modules/ROOT/pages/configuration/configuration-settings.adoc
Improve the descriptions of the `initial..` settings to emphasize that they occur only in two cases:
- When a DBMS is created (at the first DBMS startup)
- When a server is enabled (when you add a new server to the existing cluster)
=> Update descriptions of the `initial.` settings (#2587)

modules/ROOT/pages/changes-deprecations-removals.adoc, modules/ROOT/pages/clustering/multi-region-deployment/multi-data-center-routing.adoc, modules/ROOT/pages/clustering/servers.adoc, modules/ROOT/pages/clustering/setup/analytics-cluster.adoc, modules/ROOT/pages/clustering/setup/deploy.adoc, modules/ROOT/pages/configuration/configuration-settings.adoc
- To document a missing step in the guide on how to deploy an analytics cluster: you have to enable servers that are in the free state.
- To clarify the use and meaning of the initial settings when you deploy a cluster for the first time.
- To add information about the setting, allowing automatic enabling of free servers, to the section on the `ENABLED` state of servers.
=> Clarify situation when enabling servers
