- modules/ROOT/pages/tools/neo4j-admin/index.adoc
> Fix the table Available commands per category

- modules/ROOT/pages/introduction.adoc
> Remove sharded and federated composite dbs

- modules/ROOT/pages/docker/ref-settings.adoc
> Fix inconsistencies in docker settings (#642)

- modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/625
> Adding more context to the `sub` information on the SSO tutorial (#625)

- modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/625
> Adding more context to the sub information on the SSO tutorial #625

- modules/ROOT/pages/clustering/servers.adoc
Add a note for cases when deallocation can fail.
> Edge cases when deallocation is prevented

- modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
> Add a warning that neo4j-admin database upload does not support private linking

- modules/ROOT/pages/tools/neo4j-admin/push-to-cloud.adoc
> Add a warning that neo4j-admin push-to-cloud does not support private linking

- modules/ROOT/pages/backup-restore/restore-backup.adoc
> Restore is not possible to a previous version

- modules/ROOT/pages/configuration/dynamic-settings.adoc
- modules/ROOT/pages/configuration/neo4j-conf.adoc
- modules/ROOT/pages/kubernetes/configuration.adoc
This PR replaces samples of dbms.listConfig with SHOW SETTINGS statement.
Cherry-picked from #529
> Use SHOW SETTINGS instead of dbms.listConfig (#529)

- modules/ROOT/pages/installation/windows.adoc
Instead of the correct `windows-service`
> Updating a last command that was still install-service

- modules/ROOT/pages/installation/windows.adoc
Instead of the correct `windows-service`
Cherry-picked from https://github.com/neo4j/docs-operations/pull/673
> Updating a last command that was still install-service (#673)

- modules/ROOT/pages/installation/requirements.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/665
> Fixing incorrect reference (#665)

- modules/ROOT/pages/backup-restore/restore-dump.adoc
> Update parameters and  options (#680)

- modules/ROOT/pages/kubernetes/configuration.adoc
From `server.security.oidc.*` to the new `dbms.security.oidc.*`
> Update of configuration to the latest format

- modules/ROOT/pages/kubernetes/configuration.adoc
From `server.security.oidc.*` to the new `dbms.security.oidc.*`
Cherry-picked from https://github.com/neo4j/docs-operations/pull/684
> Update of configuration to the latest format (#684)

- modules/ROOT/pages/monitoring/metrics/essential.adoc
- modules/ROOT/pages/monitoring/metrics/expose.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/662
> New information about disk monitoring (#662)

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
> Update neo4j-admin database info syntax and options to reflect the code

- modules/ROOT/pages/backup-restore/restore-backup.adoc
> Update neo4j-admin database restore syntax and options to reflect the code

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-memrec.adoc
> Update neo4j-admin server memory-recommendation syntax and options to reflect the code (#691)

- modules/ROOT/pages/kubernetes/configuration.adoc
> Add disableSubPathExpr: true to plugins yaml

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
> Update import syntax & options to reflect the code (#677)

- modules/ROOT/pages/clustering/index.adoc
It wasn't listed in the table of contents there though the page is in the left-side menu
Cherry-picked from https://github.com/neo4j/docs-operations/pull/667
> Add page monitoring cluster endpoints to the index (#667)

- modules/ROOT/pages/backup-restore/offline-backup.adoc
> Update neo4j-admin database dump syntax and options to reflect the code

- modules/ROOT/pages/backup-restore/aggregate.adoc
> Update neo4j-admin database aggregate-backup syntax and options to reflect the code

- modules/ROOT/pages/clustering/servers.adoc
Regarding: https://trello.com/c/kroMaO0f/4500-5x-docs-on-server-rename
> clarify on server rename

- modules/ROOT/pages/installation/linux/debian.adoc
- modules/ROOT/pages/installation/requirements.adoc
Also added RHEL 8.8 to compatible OSs.
> updated debian install instructions for if openjdk 19 gets installed

- modules/ROOT/pages/kubernetes/configuration.adoc
Hey @harshitsinghvi22, the other lines (not related to this PR) were added to the yaml file when I pasted the new version from the helm chart repo. They seemed to be missing in the doc's version.
> Configure LDAP password through secret

- preview.yml
> Add edit url to preview playbook (#650)

- modules/ROOT/pages/installation/linux/debian.adoc
> Updated section about if java 19 is accidentally installed

- modules/ROOT/pages/reference/configuration-settings.adoc
> Add query cache (#724)

- modules/ROOT/pages/backup-restore/copy-database.adoc
> Update neo4j-admin database copy syntax and options to reflect the code

- modules/ROOT/pages/tools/neo4j-admin/unbind.adoc
> Update neo4j-admin server unbind syntax and options to reflect the code

- modules/ROOT/pages/tools/cypher-shell.adoc
> Update cypher-shell syntax and options to reflect the code (#731)

- modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
> Update upload to aura syntax and options to reflect the code (#735)

- modules/ROOT/pages/tools/neo4j-admin/migrate-configuration.adoc
> Update migrate config syntax and options to reflect the code

- modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
> Update migrate database syntax and options to reflect the code (#733)

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/tools/index.adoc
- modules/ROOT/pages/tools/neo4j-admin/validate-config.adoc
> Add neo4j-admin validate-config (#721)

- modules/ROOT/pages/monitoring/metrics/essential.adoc
- modules/ROOT/pages/monitoring/metrics/expose.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/662
> New information about disk monitoring #662

- antora.yml
This is the current patch version of 4.4.
> 4.4 update version

- modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
overhaul of GCP documentation page, to bring it in line with the Azure and AWS pages.
> GCP Doc Update

- modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
overhaul of GCP documentation page, to bring it in line with the Azure and AWS pages.
---------
Cherry-picked from #741
> GCP Doc Update (#741)

- modules/ROOT/pages/kubernetes/accessing-cluster.adoc
- modules/ROOT/pages/kubernetes/accessing-neo4j.adoc
- modules/ROOT/pages/kubernetes/quickstart-standalone/verify-installation.adoc
> Remove port-forward and the enterprise label from lb (#748)

- modules/ROOT/pages/kubernetes/accessing-neo4j.adoc
> Support for customising the targetPort and name in the LB configuration

- modules/ROOT/pages/backup-restore/offline-backup.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/758
> Updating command syntax after bug was flagged (#758)

- modules/ROOT/pages/backup-restore/copy-database.adoc
We used to have this information, but it seems to have been lost at some point
> Store copy migration info

- modules/ROOT/pages/backup-restore/copy-database.adoc
We used to have this information, but it seems to have been lost at some point
Cherry-picked from #769
> Store copy migration info (#769)

- modules/ROOT/pages/clustering/servers.adoc
- modules/ROOT/pages/configuration/neo4j-conf.adoc
Cherry-picked from #740 and #744
> 5.x release 5.8

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
> Defaults --strict option in import to false (#792)

- modules/ROOT/pages/configuration/configuration-settings.adoc
> Document db.logs.query.annotation_data_as_json_enabled (#790)

- modules/ROOT/pages/docker/operations.adoc
> Invalid NEO4J_PLUGINS values now produces a helpful error message (#793)

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/configuration/configuration-settings.adoc
> Briefly describe each config group (#800)

- modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
> Add docs for logging group results from ldap server (#822)

- modules/ROOT/pages/installation/linux/debian.adoc
> Fix list formatting (#823)

- modules/ROOT/pages/installation/linux/rpm.adoc
- modules/ROOT/pages/installation/linux/tarball.adoc
- modules/ROOT/pages/installation/osx.adoc
- modules/ROOT/pages/installation/windows.adoc
> Improve license acceptance wording (#819)

- modules/ROOT/pages/composite-databases/administration.adoc
https://trello.com/c/AisWpFW4/3423-two-identical-aliases-for-the-same-database
> Add note about quoting in CREATE ALIAS and update examples to match

- modules/ROOT/pages/introduction.adoc
- Added relationship key constraints as they were missing (node key existed)
- Added property uniqueness constraints cause there were none of them
- Added the new property type constraints (introduced in https://github.com/neo4j/docs-cypher/pull/597)
> Add new constraint types to intro table

- modules/ROOT/pages/introduction.adoc
- Added relationship key constraints as they were missing (node key existed)
- Added property uniqueness constraints cause there were none of them
- Added the new property type constraints (introduced in https://github.com/neo4j/docs-cypher/pull/597)
---------
> Add new constraint types to intro table (#834)

- modules/ROOT/pages/backup-restore/restore-backup.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/836
> Admonition message about the applicability of the option (#836)

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Add the neo4j-admin backup feature (#853)

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
> Reword the warning about the use of the incremental import (#865)

- modules/ROOT/pages/docker/operations.adoc
Trello: https://trello.com/c/Dvh6jWq7/5032-doc-apoc-extended-as-a-plugin
Corresponding 4.4 PR: https://github.com/neo4j/docs-operations/pull/872
> Update apoc plugin information 

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/configuration/plugins.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/863
> Page on installing plugins to Neo4j #863

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/configuration/plugins.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/863
> Page on installing plugins to Neo4j (#863)

- modules/ROOT/pages/configuration/configuration-settings.adoc
> Improve the description of db.tx_log.rotation.retention_policy 

- modules/ROOT/pages/configuration/configuration-settings.adoc
> add label to configs introduced in 5.7 (#887)

- modules/ROOT/pages/backup-restore/online-backup.adoc
- modules/ROOT/pages/backup-restore/restore-backup.adoc
- modules/ROOT/pages/clustering/databases.adoc
> Add examples for performing  differential backup and restore (#874)

- modules/ROOT/pages/backup-restore/copy-database.adoc
- modules/ROOT/pages/backup-restore/restore-backup.adoc
- modules/ROOT/pages/clustering/databases.adoc
> add a section about restoring a backup in a cluster

- modules/ROOT/pages/docker/ref-settings.adoc
> Fix typo in max_databases docker config

- modules/ROOT/pages/backup-restore/online-backup.adoc
> fixed table headers for db parameter in online backup docs

- modules/ROOT/pages/security/ssl-framework.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/917
> Adding information about port 7688 (#917)

- modules/ROOT/pages/security/ssl-framework.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/917
> Adding information about port 7688 #917

- modules/ROOT/pages/kubernetes/configuration.adoc
- modules/ROOT/pages/kubernetes/persistent-volumes.adoc
To be cherry-picked when Helm Charts 5.10 are released.
> Add support for PVC labels

- modules/ROOT/pages/docker/operations.adoc
> remove the table with supported plugins from docker and link to the plugins page

- modules/ROOT/pages/configuration/dynamic-settings.adoc
> update the dynamic settings (#926)

- modules/ROOT/pages/monitoring/logging.adoc
> Improve the logging page (#911)

- modules/ROOT/pages/kubernetes/configuration.adoc
- modules/ROOT/pages/kubernetes/persistent-volumes.adoc
To be cherry-picked when Helm Charts 5.10 are released.
Cherry-picked from #919
> Add support for PVC labels (#919)

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Add support for backing up multiple dbs with neo4j-admin helm (#933)

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Add support for adding nodeSelector labels with neo4j-admin helm (#937)

- modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
- modules/ROOT/pages/kubernetes/operations/assign-neo4j-pods.adoc
> Update the helm charts and add the nodeSelector for neo4j-admin (#939)

- modules/ROOT/pages/kubernetes/plugins.adoc
- preview.yml
Cherry-picked from https://github.com/neo4j/docs-operations/pull/943
> fixing typo (#943)

- modules/ROOT/pages/security/ssl-framework.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/875
> Update Netty version for latest Neo4j version (#875)

- modules/ROOT/pages/configuration/plugins.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/953
> Broken link to File locations page (#953)

- modules/ROOT/pages/composite-databases/administration.adoc
- modules/ROOT/pages/manage-databases/errors.adoc
- modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
> 5.11 cherry picks

- antora.yml
> Cherry-pick 5.11

- modules/ROOT/pages/monitoring/metrics/reference.adoc
> Document index metrics

- modules/ROOT/pages/monitoring/metrics/reference.adoc
> Add a caption to database state metrics (#980)

- modules/ROOT/pages/reference/procedures.adoc
> Make links of the removed procedures point to 4.4 (#978)

- modules/ROOT/pages/installation/requirements.adoc
> Link hardware requirements to performance (#962)

- modules/ROOT/pages/installation/index.adoc
> Uncomment the link to Docker installation (#961)

- modules/ROOT/pages/reference/procedures.adoc
Update descriptions of two procedures according to [the Trello card](https://trello.com/c/MDGjamxT)
> Update descriptions of `db.labels` and `db.relationshipTypes`

- modules/ROOT/pages/reference/procedures.adoc
Update descriptions of two procedures according to [the Trello card](https://trello.com/c/MDGjamxT)
---------
> Update descriptions of `db.labels` and `db.relationshipTypes` (#1019)

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Add support for affinity and tolerations (#1023)

- modules/ROOT/pages/kubernetes/configuration.adoc
- modules/ROOT/pages/kubernetes/plugins.adoc
Reverts neo4j/docs-operations#1026
> Revert "Add apoc.jdbc.<alias>.url and apoc.es.<key>.url in helm charts"

- modules/ROOT/pages/kubernetes/configuration.adoc
- modules/ROOT/pages/kubernetes/plugins.adoc
> Add apoc.jdbc.<alias>.url and apoc.es.<key>.url in helm charts (#1029)

- modules/ROOT/pages/installation/linux/rpm.adoc
- modules/ROOT/pages/kubernetes/multi-dc-cluster/aks.adoc
- modules/ROOT/pages/kubernetes/operations/migrate-from-labs.adoc
- modules/ROOT/pages/kubernetes/quickstart-cluster/uninstall-cleanup.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1036
> Shortening titles for better SEO (#1036)

- modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
- modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
> Fix the failing tests (#1040)

- modules/ROOT/pages/reference/procedures.adoc
Part of [CDC docs for public beta](https://trello.com/c/XoRQNjlu/3224-publish-when-public-beta-nodes-2023-cdc-documentation) 
~~**Note** This references unpublished [docs-cdc](https://github.com/neo4j/docs-cdc). Tracker for getting docs-cdc published is [here](https://trello.com/c/ERUTfxg1/108-publish-docs-cdc).~~
> Add CDC Procedure descriptions

- modules/ROOT/pages/authentication-authorization/access-control.adoc
- modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
Companion PR to https://github.com/neo4j/docs-cypher/pull/737
> Add default `LOAD ON ALL DATA` privilege to built-in roles

- modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
> Update the available Neo4j Helm charts (#1053)

- modules/ROOT/pages/monitoring/metrics/reference.adoc
Updated the documentation for metrics to include the 4 new metrics that will be added with: https://github.com/neo-technology/neo4j/pull/22339
> update bolt metrics list

- modules/ROOT/pages/reference/procedures.adoc
> Fix label misplacement

- modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
- modules/ROOT/pages/database-administration/syntax.adoc
Incorporating the content from [#735](https://github.com/neo4j/docs-cypher/pull/735/files)
> Incorporating the content from Alter database options #735

- modules/ROOT/pages/reference/procedures.adoc
* drop beta tag vector index create and query procedures
* keep beta tag on set property procedure
* deprecate old set procedure in favor of new procedure with different name and signature
> Update procedures with new set procedure and beta status

- modules/ROOT/pages/tools/cypher-shell.adoc
> Add new command `:sysinfo`

- modules/ROOT/pages/kubernetes/plugins.adoc
> added additional step to set NEO4J_PLUGINS env (#1061)

- modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
> fix the env NEO4J_DOCKER_IMAGE

- modules/ROOT/pages/installation/requirements.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1088
> Adding information about JRE (#1088)

- modules/ROOT/pages/security/ssl-framework.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1089
> Adding note about OS processor version and OpenSSL (#1089)

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/configuration/command-expansion.adoc
- modules/ROOT/pages/docker/clustering.adoc
- modules/ROOT/pages/kubernetes/operations/maintenance-mode.adoc
- modules/ROOT/pages/manage-databases/remote-alias.adoc
- modules/ROOT/pages/security/ssl-framework.adoc
- modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1108
> Moving the command expansion section to a new page (#1108)

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/configuration/command-expansion.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1108
> Moving the command expansion section to a new page #1108

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/configuration/command-expansion.adoc
- modules/ROOT/pages/kubernetes/operations/maintenance-mode.adoc
- modules/ROOT/pages/manage-databases/remote-alias.adoc
- modules/ROOT/pages/security/ssl-framework.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1108
> 4.4 cherry pick 1108

- modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
> rename ingress.yaml to ingress-values.yaml (#1132)

- antora.yml
- modules/ROOT/pages/reference/procedures.adoc
> 5.x cherry picks 5.13

- modules/ROOT/pages/authentication-authorization/access-control.adoc
- modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
- modules/ROOT/pages/reference/procedures.adoc
Cherry-picks #1046, #1044, and #1063
> 5.x cherry picks for 5.13 part 2

- modules/ROOT/pages/clustering/databases.adoc
- modules/ROOT/pages/clustering/monitoring/show-databases-monitoring.adoc
- modules/ROOT/pages/database-administration/standard-databases/errors.adoc
- modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
> rearranged to accommodate all possible database states (#1045)

- modules/ROOT/pages/clustering/disaster-recovery.adoc
Update error message encountered on disaster recovery path when recovering servers.
> Update error message when user database has lost quorum

- modules/ROOT/pages/clustering/disaster-recovery.adoc
Update error message encountered on disaster recovery path when recovering servers.
---------
> Update error message when user database has lost quorum (#1136)

- modules/ROOT/pages/kubernetes/quickstart-cluster/access-inside-k8s.adoc
- modules/ROOT/pages/kubernetes/quickstart-standalone/verify-installation.adoc
> Remove port 7473 from the services (#1152)

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> adding support for workload identity in neo4j admin backup (#1131)

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Cherry-picks #1131 and updates the version and the yaml file.
> 4.4 workload identity

- modules/ROOT/pages/authentication-authorization/index.adoc
- modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
- modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Information about mixed-mode authentication and/or authorization should be added to the `4.4` branch as well.
---------
> Document mixed-mode authentication and authorization (#1126)

- modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
CDC feature flag was enabled by default recently
> Remove test-skip anotations for cdc docs

- modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
CDC feature flag was enabled by default recently
Cherry-picked from #1167
> Remove test-skip anotations for cdc docs (#1167)

- modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1159
> Adding description related to composite databases (#1159)

- modules/ROOT/pages/installation/linux/rpm.adoc
also we should be including branch number in the script for adding our rpm repository (like we already do for 5x)
> added note about clearing yum cache on upgrade

- modules/ROOT/pages/installation/linux/rpm.adoc
> added note about clearing yum cache on upgrade (#1115)

- modules/ROOT/pages/security/ssl-framework.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1178
> Updating information about netty files after neo4j 5.12 (#1178)

- modules/ROOT/pages/reference/procedures.adoc
Update descriptions and modes of the procedures according to the [test results](https://trello.com/c/bCR3TJOn)
> Update procedures descriptions and modes according to the test results

- modules/ROOT/pages/security/ssl-framework.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1177
> Improvement of instructions for SSL configuration (#1177)

- modules/ROOT/pages/kubernetes/persistent-volumes.adoc
> fix a typo in k8s (#1196)

- modules/ROOT/pages/authentication-authorization/introduction.adoc
- modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
- modules/ROOT/pages/authentication-authorization/sso-integration.adoc
> Add information about mixed-mode auth

- modules/ROOT/pages/authentication-authorization/manage-users.adoc
Explain the effect of suspending a user that is currently using the system.
> Improve documentation for suspended users

- modules/ROOT/pages/authentication-authorization/manage-users.adoc
Explain the effect of suspending a user that is currently using the system.
---------
Cherry-picked from #1183
> Improve documentation for suspended users (#1183)

- modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1208
> Fixing path to neo4j.config (#1208)

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Add support for MinIO

- modules/ROOT/pages/monitoring/metrics/reference.adoc
According to the test results, we have to update some of the metric descriptions.
> Update descriptions of metrics according to the test results

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Remove AWS from the MinIO (#1229)

- modules/ROOT/pages/backup-restore/online-backup.adoc
> adding clarification to `neo4j-admin backup` command description (#1227)

- modules/ROOT/pages/kubernetes/plugins.adoc
Removed the section where we installed apoc with the env ["apoc"]. This is not needed if we are just pointing to the file in labs.
---------
Cherry-picked from #1240
> Update plugins.adoc in Kubernetes (#1240)

- modules/ROOT/pages/monitoring/metrics/reference.adoc
To fetch recent updates made to the metrics descriptions in the PR#23406. Those updates will be visible for customers in 5.16
> Update cluster related metrics

- modules/ROOT/pages/backup-restore/online-backup.adoc
Copied from #1227
@phil198, could you also update the description in the codebase so that it reflects the docs?
> adding clarification to neo4j-admin backup command description

- modules/ROOT/pages/configuration/neo4j-conf.adoc
No changes in the content as they are the same.
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1259
> Removing duplicate content about command expansion (#1259)

- modules/ROOT/pages/configuration/ports.adoc
> Remove mention of SINGLE mode

- modules/ROOT/pages/configuration/ports.adoc
> Remove mention of SINGLE mode (#1266)

- modules/ROOT/pages/introduction.adoc
Cherry-picked and adapted from https://github.com/neo4j/docs-operations/pull/1258
> Restructure of the introduction page (#1258)

- modules/ROOT/pages/tools/neo4j-admin/validate-config.adoc
> Fix neo4j-admin server validate-config example (#1243)

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
- modules/ROOT/pages/configuration/index.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1260
> Moving the password page to auth (#1260)

- modules/ROOT/pages/configuration/index.adoc
From this https://github.com/neo4j/docs-operations/pull/1285
> Undoing merged changes

- modules/ROOT/pages/reference/procedures.adoc
Paired with https://github.com/neo4j/docs-cypher/pull/824
> db.index.vector.createNodeIndex replaced by CREATE VECTOR INDEX

- modules/ROOT/pages/reference/procedures.adoc
Paired with https://github.com/neo4j/docs-cypher/pull/824
Cherry-picked from #1295
> db.index.vector.createNodeIndex replaced by CREATE VECTOR INDEX (#1295)

- modules/ROOT/pages/installation/requirements.adoc
> Add support for Amazon Linux 2023 AMI (#1271)

- modules/ROOT/pages/backup-restore/index.adoc
> Remove the EE label from the backup and restore index page (#1310)

- modules/ROOT/pages/configuration/configuration-settings.adoc
Depends on https://github.com/neo-technology/neo4j/pull/23324
> Update the default value of dbms.record_format

- modules/ROOT/pages/cloud-deployments/index.adoc
- modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
- modules/ROOT/pages/cloud-deployments/neo4j-azure.adoc
- modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1270
> Removing enterprise label from cloud deployment pages #1270

- modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
Related to https://github.com/neo4j/docs-operations/pull/1270
> Fixing typo in url

- modules/ROOT/pages/backup-restore/online-backup.adoc
Cherry-picked from #1217. Depends on https://github.com/neo-technology/neo4j/pull/23391
> Neo4-admin-backup-globbing 

- modules/ROOT/pages/configuration/index.adoc
Rename the section title according to the recent changes in page _Configure network connectors_. See PR #1301
> Rename the section according to the TOC

- modules/ROOT/pages/configuration/index.adoc
Rename the section title according to the recent changes in page _Configure network connectors_. See PR #1301
> Rename the section according to the TOC (#1332)

- modules/ROOT/pages/installation/linux/debian.adoc
- modules/ROOT/pages/installation/linux/rpm.adoc
- modules/ROOT/pages/installation/linux/systemd.adoc
- modules/ROOT/pages/installation/linux/tarball.adoc
- modules/ROOT/pages/installation/osx.adoc
- modules/ROOT/pages/installation/windows.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1331
> Add uninstallation steps (#1331)

- modules/ROOT/pages/configuration/configuration-settings.adoc
> fix mismatching configs (#1340)

- modules/ROOT/pages/backup-restore/aggregate.adoc
- modules/ROOT/pages/backup-restore/online-backup.adoc
- modules/ROOT/pages/backup-restore/restore-backup.adoc
> update the backup and restore commands (#1354)

- modules/ROOT/pages/database-internals/transaction-logs.adoc
> Add a link from configure retention to dynamic settings

- modules/ROOT/pages/clustering/setup/deploy.adoc
> add a page alias for deploy a cluster

- modules/ROOT/pages/configuration/configuration-settings.adoc
> update the description of db.format to include block

- modules/ROOT/pages/backup-restore/copy-database.adoc
- modules/ROOT/pages/configuration/configuration-settings.adoc
- modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
> Add block format to copy, migrate, and configs (#1349)

- modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
Depends on https://github.com/neo-technology/neo4j/pull/24011
> update the description of --from-path

- modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
> Fix a typo in k8s docs

- modules/ROOT/pages/configuration/configuration-settings.adoc
Depends on https://github.com/neo-technology/neo4j/pull/24023
> update the descrption of dbms.cluster.discovery.resolver_type

- modules/ROOT/pages/configuration/file-locations.adoc
Split the original table into several pieces depending on the file type
> Restructure the table of file def locations

- modules/ROOT/pages/configuration/configuration-settings.adoc
> update the description of dbms.cluster.discovery.resolver_type (#1386)

- modules/ROOT/pages/configuration/file-locations.adoc
Split the original table into several pieces depending on the file type
> Restructure the table of file def locations (#1330)

- modules/ROOT/pages/introduction.adoc
> Add vector indexes to the available features table (#1402)

- modules/ROOT/pages/database-internals/store-formats.adoc
- modules/ROOT/pages/introduction.adoc
> Remove beta label from Block format (#1410)

- modules/ROOT/pages/installation/windows.adoc
> Update the Windows installation steps (#1413)

- modules/ROOT/pages/reference/procedures.adoc
> Add genai.vector.encodeBatch to the list of procedures (#1412)

- modules/ROOT/pages/kubernetes/configuration.adoc
- modules/ROOT/pages/kubernetes/quickstart-cluster/create-value-file.adoc
> Helm Chart installs Community Edition by default (#1417)

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Add support for backing up a database to on-prem storage (#1418)

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
> Fix missing quote in admin-import property types section (#1422)

- modules/ROOT/pages/database-internals/store-formats.adoc
- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
> Update the store  format page (#1421)

- modules/ROOT/pages/configuration/dynamic-settings.adoc
Was missed when added to main list https://github.com/neo4j/docs-operations/commit/9e609fab16114825bb043d1434e53e8de6596923
> Add `dbms.cluster.network.connect_timeout` to dynamic settings list.

- modules/ROOT/pages/monitoring/metrics/reference.adoc
Make metric classes more visible.
> Add third-level titles to the Metrics ref page

- modules/ROOT/pages/monitoring/metrics/reference.adoc
Make metric classes more visible.
> Add third-level titles to the Metrics ref page (#1435)

- modules/ROOT/pages/tools/neo4j-admin/index.adoc
- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
> Add support for providing args in a file (#1441)

- modules/ROOT/pages/backup-restore/restore-backup.adoc
> remove the note about dropping the database (#1454)

- modules/ROOT/pages/backup-restore/online-backup.adoc
- modules/ROOT/pages/index.adoc
> Remove legacy-backup and legacy-restore (#1461)

- modules/ROOT/pages/installation/linux/tarball.adoc
- modules/ROOT/pages/installation/osx.adoc
- modules/ROOT/pages/installation/windows.adoc
> Add a step to decouple the conf and data folders from the binaries (#1457)

- modules/ROOT/pages/kubernetes/index.adoc
- modules/ROOT/pages/kubernetes/operations/index.adoc
- modules/ROOT/pages/kubernetes/operations/upgrade.adoc
> Reorganize the upgrade on k8s page and change the title (#1460)

- modules/ROOT/pages/authentication-authorization/limitations.adoc
- modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
- modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
as well as notes on the relevant privileges linking to it
> Add section on limitations around privileges and missing labels

- modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
> update the reverse-proxy yaml to support privilege and access control settings for a Container (#1459)

- modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
- modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
- modules/ROOT/pages/authentication-authorization/manage-users.adoc
- modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
- modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
- modules/ROOT/pages/cloud-deployments/neo4j-azure.adoc
- modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
- modules/ROOT/pages/clustering/servers.adoc
- modules/ROOT/pages/configuration/configuration-settings.adoc
- modules/ROOT/pages/configuration/set-initial-password.adoc
- modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
- modules/ROOT/pages/database-internals/checkpointing.adoc
- modules/ROOT/pages/database-internals/transaction-logs.adoc
- modules/ROOT/pages/database-internals/transaction-management.adoc
- modules/ROOT/pages/docker/introduction.adoc
- modules/ROOT/pages/kubernetes/authentication-authorization.adoc
- modules/ROOT/pages/kubernetes/persistent-volumes.adoc
- modules/ROOT/pages/monitoring/metrics/reference.adoc
- modules/ROOT/pages/reference/procedures.adoc
- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
- modules/ROOT/pages/tools/neo4j-admin/validate-config.adoc
Using the new `role=label--` notation for roles/labels on headings and block elements.
> Replace labels with roles

- modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
- modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
- modules/ROOT/pages/authentication-authorization/manage-users.adoc
- modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
- modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
- modules/ROOT/pages/cloud-deployments/neo4j-azure.adoc
- modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
- modules/ROOT/pages/clustering/servers.adoc
- modules/ROOT/pages/configuration/configuration-settings.adoc
- modules/ROOT/pages/configuration/set-initial-password.adoc
- modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
- modules/ROOT/pages/database-internals/checkpointing.adoc
- modules/ROOT/pages/database-internals/transaction-logs.adoc
- modules/ROOT/pages/database-internals/transaction-management.adoc
- modules/ROOT/pages/docker/introduction.adoc
- modules/ROOT/pages/kubernetes/authentication-authorization.adoc
- modules/ROOT/pages/kubernetes/persistent-volumes.adoc
- modules/ROOT/pages/monitoring/metrics/reference.adoc
- modules/ROOT/pages/reference/procedures.adoc
- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
- modules/ROOT/pages/tools/neo4j-admin/validate-config.adoc
Using the new `role=label--` notation for roles/labels on headings and block elements.
Cherry-picked from #1473
> Replace labels with roles (#1473)

- modules/ROOT/pages/database-internals/store-formats.adoc
> Improve Changing the store format (#1475)

- modules/ROOT/pages/tools/neo4j-admin/index.adoc
- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
> Add a note about using additional-config with the import command (#1477)

- modules/ROOT/pages/reference/procedures.adoc
> Add a note about LIST<INTEGER | FLOAT> (#1491)

- modules/ROOT/pages/configuration/file-locations.adoc
- modules/ROOT/pages/installation/requirements.adoc
> Fix dbms.jvm.additionalto be server.jvm.additional (#1494)

- modules/ROOT/pages/backup-restore/restore-backup.adoc
Depends on https://github.com/neo-technology/neo4j/pull/24305
> Editorial review of the descriptions of the restore options

- modules/ROOT/pages/configuration/file-locations.adoc
- modules/ROOT/pages/installation/requirements.adoc
> Add information for using JNA (#1499)

- modules/ROOT/pages/backup-restore/modes.adoc
- modules/ROOT/pages/backup-restore/online-backup.adoc
- modules/ROOT/pages/backup-restore/restore-dump.adoc
- modules/ROOT/pages/clustering/disaster-recovery.adoc
- modules/ROOT/pages/clustering/setup/single-to-cluster.adoc
- modules/ROOT/pages/database-internals/store-formats.adoc
- modules/ROOT/pages/tools/neo4j-admin/migrate-configuration.adoc
- modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
> 5.x neo4j paths

- modules/ROOT/partials/neo4j-config/all-settings.adoc
> Update the description of dbms.track_query_cpu_time

- modules/ROOT/partials/neo4j-config/all-settings.adoc
> Update the description of dbms.track_query_cpu_time (#1516)

- modules/ROOT/pages/backup-restore/offline-backup.adoc
> Improve the dump page and add default location for the dumps (#1498)

- modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
- modules/ROOT/pages/clustering/databases.adoc
- modules/ROOT/pages/clustering/setup/discovery.adoc
- modules/ROOT/pages/clustering/setup/encryption.adoc
- modules/ROOT/pages/clustering/setup/routing.adoc
> Add page-aliases to the clustering section (#1509)

- modules/ROOT/pages/reference/procedures.adoc
Make changes to the 4th column of the table _Removed procedures in 5.0_:
- rename the table header **Comment** to **Replaced by**
- remove unnecessary details
> Improve the Removed procedures section

- modules/ROOT/pages/reference/procedures.adoc
Make changes to the 4th column of the table _Removed procedures in 5.0_:
- rename the table header **Comment** to **Replaced by**
- remove unnecessary details
> Improve the Removed procedures section (#1514)

- modules/ROOT/pages/backup-restore/online-backup.adoc
> Add an example to the online backup with lists of database names (#1507)

- modules/ROOT/pages/database-internals/store-formats.adoc
- package-lock.json
> Update the steps for changing the store format in a cluster (#1526)

- modules/ROOT/pages/reference/procedures.adoc
I ordered both the labels and roles, but the roles are displayed alphabetically instead of in the specified order.
> Order the procedure labels

- modules/ROOT/pages/reference/procedures.adoc
> Order the procedure labels (#1528)

- modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
> Title was missing a word (#1537)

- modules/ROOT/pages/kubernetes/monitoring.adoc
> Update monitoring.adoc: fixed typo

- modules/ROOT/pages/configuration/configuration-settings.adoc
> Fix config mismatches (#1539)

- modules/ROOT/pages/installation/linux/rpm.adoc
> Update the steps for installing Neo4j via a package installer (#1546)

- modules/ROOT/pages/monitoring/metrics/reference.adoc
> Add missing metric <prefix>.transaction.validation_failure (#1544)

- modules/ROOT/pages/backup-restore/aggregate.adoc
- modules/ROOT/pages/backup-restore/copy-database.adoc
- modules/ROOT/pages/backup-restore/restore-dump.adoc
Depends on https://github.com/neo-technology/neo4j/pull/24995, https://github.com/neo-technology/neo4j/pull/24993, and https://github.com/neo-technology/neo4j/pull/24992.
> Fix mismatches in the backup and restore section

- modules/ROOT/pages/configuration/configuration-settings.adoc
Replaces #838 
Depends on https://github.com/neo-technology/neo4j/pull/25103
> Improve the checkpoint setting descriptions

- modules/ROOT/pages/installation/linux/debian.adoc
- modules/ROOT/pages/installation/linux/tarball.adoc
- modules/ROOT/pages/installation/neo4j-desktop.adoc
- modules/ROOT/pages/installation/osx.adoc
- modules/ROOT/pages/installation/windows.adoc
- modules/ROOT/pages/tools/cypher-shell.adoc
To make it consistent with the main website page.
> Rename Download center to Deployment center

- modules/ROOT/pages/configuration/configuration-settings.adoc
…ader`, `server.http.transaction_idle_timeout`
> Add new configs `dbms.security.http_static_content_security_policy_header`, `server.http.transaction_idle_timeout`

- modules/ROOT/pages/backup-restore/restore-backup.adoc
- modules/ROOT/pages/backup-restore/restore-dump.adoc
- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1600
> Updating link to CDC after structural changes in the docset (#1600)

- modules/ROOT/pages/kubernetes/configuration.adoc
This is the copy of the PR #1590
> Fix the error about the Neo4j Helm chart and service account

- modules/ROOT/pages/installation/index.adoc
- modules/ROOT/pages/introduction.adoc
Depends on https://github.com/neo-technology/docs-home/pull/112
> add a link to anonymous usage data report

- modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
- modules/ROOT/pages/database-internals/store-formats.adoc
> Document the storeFormat option for create database (#1577)

- modules/ROOT/pages/tools/neo4j-admin/index.adoc
> Add some possible options for neo4j-admin server license (#1606)

- modules/ROOT/pages/kubernetes/configuration.adoc
- modules/ROOT/pages/kubernetes/quickstart-cluster/create-value-file.adoc
- modules/ROOT/pages/kubernetes/quickstart-cluster/prerequisites.adoc
- modules/ROOT/pages/kubernetes/quickstart-standalone/create-value-file.adoc
- modules/ROOT/pages/kubernetes/quickstart-standalone/prerequisites.adoc
> Add eval option to neo4j.acceptLicenseAgreement (#1605)

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/configuration/configuration-settings.adoc
- modules/ROOT/pages/database-internals/concurrent-data-access.adoc
- modules/ROOT/pages/database-internals/index.adoc
- modules/ROOT/pages/database-internals/transaction-management.adoc
Slightly restructure locking section to accommodate these changes.
> Document anomalies under read-committed.

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/configuration/configuration-settings.adoc
- modules/ROOT/pages/database-internals/concurrent-data-access.adoc
- modules/ROOT/pages/database-internals/index.adoc
- modules/ROOT/pages/database-internals/transaction-management.adoc
Slightly restructure locking section to accommodate these changes.
---------
Cherry-picked from #1601
> Document anomalies under read-committed. (#1601)

- modules/ROOT/pages/installation/linux/rpm.adoc
> Remove the note that Neo4j supports SELinux by default

- modules/ROOT/pages/backup-restore/planning.adoc
> Fix a typo that says backup can compact data store (#1634)

- modules/ROOT/pages/backup-restore/online-backup.adoc
- modules/ROOT/pages/backup-restore/restore-backup.adoc
- modules/ROOT/pages/backup-restore/restore-dump.adoc
- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Linked to https://github.com/neo-technology/neo4j/pull/25663
> Fixes to backup-restore section to match product and prepare for tests

- modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
- modules/ROOT/pages/clustering/settings.adoc
- modules/ROOT/pages/configuration/configuration-settings.adoc
- modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Depends on https://github.com/neo-technology/neo4j/pull/25527
> Improve the cluster config descriptions

- modules/ROOT/pages/authentication-authorization/manage-roles.adoc
- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
- modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
Depends on https://github.com/neo-technology/neo4j/pull/25631
> improve the description of import format option

- modules/ROOT/pages/configuration/configuration-settings.adoc
- modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
Depends on https://github.com/neo-technology/neo4j/pull/25751
> Prepare the connection setting descriptions for testing

- modules/ROOT/pages/configuration/configuration-settings.adoc
New configuration setting for inferring labels.
Also see https://github.com/neo4j/docs-cypher/pull/958
Depends on https://github.com/neo-technology/neo4j/pull/25767
> Describe setting to infer labels.

- modules/ROOT/pages/performance/index-configuration.adoc
> Fix the wrong Cypher commands for showing a specific index and a few typos (#1662)

- modules/ROOT/pages/tools/cypher-shell.adoc
Depends on https://github.com/neo-technology/neo4j/pull/25803
> Editorial update of the cypher shell help to prepare for docs testing

- modules/ROOT/pages/installation/index.adoc
- modules/ROOT/pages/introduction.adoc
Depends on https://github.com/neo-technology/neo4j/pull/25797
> Rename the underscore in https://neo4j.com/docs/usage_data/ with a hyphen

- modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
> Aura instance must be accessible from the machine running `neo4j-admin`

- modules/ROOT/pages/configuration/configuration-settings.adoc
based on the PR https://github.com/neo-technology/neo4j/pull/25745
See also https://github.com/neo-technology/neo4j/pull/25885
> Add new configs for full-text indexes

- modules/ROOT/pages/authentication-authorization/database-administration.adoc
- modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
- modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
> Clarity the token/NAME MANAGEMENT privilege (#1674)

- modules/ROOT/pages/clustering/databases.adoc
> Replace comma with period (#1677)

- modules/ROOT/pages/backup-restore/restore-backup.adoc
> Fix the formatting in Restore a full backup section (#1678)

- modules/ROOT/pages/clustering/intra-cluster-encryption.adoc
- modules/ROOT/pages/security/ssl-framework.adoc
> Add a tip about needing server and client usage in intra-cluster TLS certificates

- modules/ROOT/pages/monitoring/metrics/reference.adoc
Describe two new public metrics of lighthouse
@yirensum additional context - https://neo4j.atlassian.net/wiki/spaces/Cluster/pages/511606802/Lighthouse+GA+plan
> Add new lighthouse metrics

- modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Related to: https://github.com/neo-technology/neo4j/pull/26072
> Fix group to role mapping section

- modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Related to: https://github.com/neo-technology/neo4j/pull/26072
Cherry-picked from #1699
> Fix group to role mapping section (#1699)

- modules/ROOT/pages/installation/linux/debian.adoc
> Replace deprecated apt-key with keyrings (#1710)

- modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
> Fix broken link to Aura docs (#1713)

- modules/ROOT/pages/tools/neo4j-admin/push-to-cloud.adoc
> Fix the link to vpc isolation aura page

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Aggregate backup in neo4j-admin helm chart (#1719)

- modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
- modules/ROOT/pages/kubernetes/configuration.adoc
> dropping all capabilities of containerSecurityContext (#1729)

- modules/ROOT/pages/configuration/configuration-settings.adoc
- modules/ROOT/pages/reference/procedures.adoc
Both initial settings and procedure to set.
Counterpart of https://github.com/neo-technology/neo4j/pull/26599
> Deprecate database allocator

- modules/ROOT/partials/aws-s3-credentials.adoc
> use a bucket policy to grant permissions to access the bucket (#1734)

- modules/ROOT/pages/configuration/configuration-settings.adoc
Labels are not needed for testing anymore, as of https://github.com/neo4j/docs-testing/commit/f6ecaa895cc75153d9c6e5bab12f721c0c780430 .
The failing tests are unrelated to this PR.
> Remove commented out labels in favor of roles.

- modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
Fix the following: 
- the config - `dbms.directories.dumps.root` → `server.directories.dumps.root`
- `neo4j-admin dump` command → `neo4j-admin database dump`
- `neo4j-admin load` command → `neo4j-admin database load`
> Update the page on how to delete db

- modules/ROOT/pages/installation/linux/debian.adoc
- modules/ROOT/pages/installation/linux/tarball.adoc
- modules/ROOT/pages/installation/osx.adoc
- modules/ROOT/pages/installation/windows.adoc
see also [PR#1782](https://github.com/neo4j/docs-operations/pull/1782)
> Change http to https in links to external sites

- modules/ROOT/pages/backup-restore/aggregate.adoc
- modules/ROOT/pages/backup-restore/online-backup.adoc
- modules/ROOT/pages/backup-restore/restore-backup.adoc
This PR is related to adding a new `--temp-path` option that was merged in https://github.com/neo-technology/neo4j/pull/26359
> Add docs related to public --temp-path option in backup related commands

- modules/ROOT/pages/reference/procedures.adoc
related to the [PR#26817](https://github.com/neo-technology/neo4j/pull/26817)
> Change the signature for the `dbms.cluster.checkConnectivity` procedure

- modules/ROOT/pages/configuration/connectors.adoc
Copy the [PR#1796](https://github.com/neo4j/docs-operations/pull/1796)
> Fix the default name of `listen_address`

- modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
- modules/ROOT/pages/authentication-authorization/manage-roles.adoc
Update the column information to not just be in the text but as proper tables for the 2 show commands that didn't have them as tables already.
Cherry-picked from #1826
> Show columns clarifications (#1826)

- modules/ROOT/pages/database-internals/store-formats.adoc
> Warn users that changing the store format also changes the built-in id property and elementID

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
We think it probably works, we just haven't tested it. So let's not say one way or the other just yet.
> Removed message about no TLS/SSL support for Minio.

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
https://trello.com/c/oAjKlzc1/522-improvement-update-documentation-example-for-k8s-on-premises-backup
> Add an empty value for cloud provider

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Add an empty value for cloud provider (#1869)

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
> Add footnote that --schema is not supported in 5.24 (#1870)

- modules/ROOT/pages/tools/neo4j-admin/push-to-cloud.adoc
See also https://github.com/neo4j/docs-operations/pull/1862
> draganddrop4.4

- modules/ROOT/pages/security/ssl-framework.adoc
> Add TLSv1.3 as an option in SSL framework section (#1886)

- modules/ROOT/pages/installation/requirements.adoc
Cherry-picked from https://github.com/neo4j/docs-operations/pull/1940
> Add supported file systems to the requirements page (#1940)

- modules/ROOT/pages/configuration/file-locations.adoc
> Products folder in CE vs EE (#1936)

- modules/ROOT/pages/backup-restore/restore-dump.adoc
> replacing an existing database is only for EE (#1937)

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
> Clarify  neo4j-admin server report --database option (#1946)

- modules/ROOT/pages/backup-restore/aggregate.adoc
- modules/ROOT/pages/backup-restore/offline-backup.adoc
- modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
> Remove the backticks around * and ? to fix the failing test (#1955)

- modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
- modules/ROOT/pages/backup-restore/copy-database.adoc
- modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
- modules/ROOT/pages/database-administration/aliases/naming-aliases.adoc
- modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
> Using quoting instead of escaping with backticks (#1959)

- modules/ROOT/pages/configuration/configuration-settings.adoc
> Update the configurations (#1964)

- modules/ROOT/pages/configuration/configuration-settings.adoc
Add deprecation labels according to the test results
> Add deprecation labels to configs

- modules/ROOT/pages/monitoring/logging.adoc
> Update the debug.log descriptions to emphasize that change of format must not be changed (#1997)

- modules/ROOT/pages/configuration/configuration-settings.adoc
- modules/ROOT/pages/installation/index.adoc
- modules/ROOT/pages/introduction.adoc
> Remove anonymous from usage data (#2012)

- modules/ROOT/pages/authentication-authorization/database-administration.adoc
- modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
- modules/ROOT/pages/database-internals/concurrent-data-access.adoc
> Add GQLSTATUS code to Neo. code (#2008)

- modules/ROOT/pages/installation/requirements.adoc
I'll make a similar PR for the LTS branch.
> updated system requirements to remove deprecated OSs

- modules/ROOT/pages/monitoring/logging.adoc
> Document executionPlanCacheKeyHash and executableQueryCacheHit (#2064)

- modules/ROOT/pages/installation/linux/tarball.adoc
- modules/ROOT/pages/installation/osx.adoc
- modules/ROOT/pages/installation/windows.adoc
> Update the TAR/ZIP steps to include decoupling of files from binaries (#2092)

- modules/ROOT/pages/index.adoc
> Small typo fix on start page (#2100)

- modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
- modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
- modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
- modules/ROOT/pages/database-administration/syntax.adoc
> Add links to the Components of the graph privilege commands from where HOME GRAPH is mentioned (#2102)

- modules/ROOT/pages/configuration/configuration-settings.adoc
Update descriptions according to the https://github.com/neo-technology/neo4j/pull/28986
> Update the discovery settings for the 5.26.2 release

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Update according to the https://github.com/neo-technology/neo4j/pull/29409
> Update the description of `update-all-matching-relationships`

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
> Emphasize in docs that in clustering environments, when using incremental import the updated database must be reseeded (#2093)

- .github/workflows/docs-branch-checks.yml
- .github/workflows/docs-pr-checks.yml
- .github/workflows/docs-teardown.yml
Note that `branch-checks` is an experimental workflow
> Workflows 1.2.0

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Update the version in all K8s backup-restore examples to be the latest

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Update the version in all K8s backup-restore examples to be the latest (#2149)

- modules/ROOT/pages/monitoring/logging.adoc
related to https://github.com/neo-technology/neo4j/pull/28252
> Add info about the `queryLang` field (#2155)

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/database-administration/syntax.adoc
> Change Cypher syntax for administration commands to Database management command syntax

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/database-administration/syntax.adoc
> Change Cypher syntax for administration commands to Database management command syntax (#2164)

- modules/ROOT/pages/kubernetes/quickstart-cluster/access-inside-k8s.adoc
> Update the command for running cypher shell in a pod to access a cluster (#2169)

- modules/ROOT/pages/backup-restore/offline-backup.adoc
- modules/ROOT/pages/backup-restore/planning.adoc
- modules/ROOT/pages/backup-restore/restore-dump.adoc
> Update dump/load that for CE you must stop the whole DBMS (#2168)

- modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
To make the page consistent with other pages.
> Turn examples into sections

- modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
To make the page consistent with other pages.
---------
> Turn examples into sections (#2201)

- modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
> Disallow unquoted database names with dot

- publish.yml
> Fix promo image, icon etc

- modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
> Update column info for show databases to mention where composite databases return null (#2212)

- modules/ROOT/pages/clustering/setup/discovery.adoc
> Fix a broken link to the K8s official docs (#2214)

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
> Update the examples of display store information (#2231)

- modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
> Update store info examples

- modules/ROOT/pages/tutorial/index.adoc
- modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
> Update Okta examples (#2185)

- modules/ROOT/pages/changes-deprecations-removals.adoc
- modules/ROOT/pages/database-administration/standard-databases/migrate-database.adoc
> Document max-off-heap-memory and the deprecation of --pagecache (#2263)

- modules/ROOT/pages/clustering/databases.adoc
- modules/ROOT/pages/configuration/configuration-settings.adoc
- modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
- modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
- modules/ROOT/pages/procedures.adoc
> Database alias can now be used as default database (#2265)

- modules/ROOT/pages/backup-restore/restore-backup.adoc
- modules/ROOT/pages/tutorial/causal-backup-restore-db.adoc
> Fix the path and name of metadata_script.cypher

- modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> Add tempDir to the aggregate command in K8s (#2292)

- modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
> Fix formatting issue due to missing ` (#2293)

- modules/ROOT/pages/backup-restore/restore-backup.adoc
> Reword the note about creating a database after restoring a CDC enabled database (#2291)

- modules/ROOT/pages/monitoring/metrics/reference.adoc
> Cypher25 ddm no block

- modules/ROOT/pages/monitoring/metrics/reference.adoc
> Document metrics reporting -1 on block format.

- modules/ROOT/pages/docker/clustering.adoc
- modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
> Fix cluster related Docker env variables

- modules/ROOT/pages/changes-deprecations-removals.adoc
A similar one https://github.com/neo4j/docs-status-codes/pull/313
> Error messages are deprecated (#2330)

- modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
- modules/ROOT/pages/backup-restore/planning.adoc
- modules/ROOT/pages/configuration/file-locations.adoc
- modules/ROOT/pages/database-administration/queries.adoc
- modules/ROOT/pages/docker/operations.adoc
- modules/ROOT/pages/installation/linux/debian.adoc
- modules/ROOT/pages/installation/linux/rpm.adoc
- modules/ROOT/pages/introduction.adoc
- modules/ROOT/pages/performance/memory-configuration.adoc
- modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
- modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Some leftovers to fix after restructuring the Tools section.
> Fix `xref` related syntax (#2349)

- modules/ROOT/pages/installation/requirements.adoc
This needs cherry picking to 5.26 LTS
> added RHEL 9.6 to supported OS table

- modules/ROOT/pages/changes-deprecations-removals.adoc
> Update deprecations and removals for the June release (#2439)

- modules/ROOT/pages/installation/requirements.adoc
This needs cherry picking to 5.26 LTS
> added RHEL 9.6 to supported OS table (#2446)

- modules/ROOT/pages/import.adoc
Unsure if this should be inline with the header or appear after the header.
Searched the repository for comparable situations but haven't found any. Both looks ... both have their pros and cons ;)
---------
> Clarify version for parquet header support. (#2489)

- modules/ROOT/pages/introduction.adoc
This is a suggestion to improve the table formatting. I raised the PR against the `5.x` branch. If we like this improvement, we can cherry-pick it to `dev` and `main` branches.
> Improve the table formatting (#2453)

- modules/ROOT/pages/database-administration/standard-databases/upload-to-aura.adoc
https://trello.com/c/qQJjbYjA/528-remove-open-a-support-ticket-requirement-with-neo4j-admin-database-upload
> remove 'open a support ticket' requirement with neo4j-admin database upload

- modules/ROOT/pages/database-administration/standard-databases/upload-to-aura.adoc
https://trello.com/c/qQJjbYjA/528-remove-open-a-support-ticket-requirement-with-neo4j-admin-database-upload
---------
> remove 'open a support ticket' requirement with neo4j-admin database upload (#2526)

- modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
- modules/ROOT/pages/introduction.adoc
- modules/ROOT/pages/monitoring/metrics/essential.adoc
- modules/ROOT/pages/performance/index-configuration.adoc
- modules/ROOT/pages/procedures.adoc
To update the links to the Cypher manual following the renaming of several pages.
---------
> Fix broken links (#2548)

- modules/ROOT/pages/configuration/configuration-settings.adoc
Based on https://github.com/neo-technology/neo4j/pull/33061 and #2612. Replaces #2612.
> Fix some typos in the configuration settings and update one description (#2620)

- modules/ROOT/pages/configuration/configuration-settings.adoc
Depends on https://github.com/neo-technology/neo4j/pull/33214
> Document config_server.metrics.deny_filter
